// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAutoUserProvisioningRuleClient creates a new instance of MockAutoUserProvisioningRuleClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAutoUserProvisioningRuleClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAutoUserProvisioningRuleClient {
	mock := &MockAutoUserProvisioningRuleClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAutoUserProvisioningRuleClient is an autogenerated mock type for the AutoUserProvisioningRuleClient type
type MockAutoUserProvisioningRuleClient struct {
	mock.Mock
}

type MockAutoUserProvisioningRuleClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAutoUserProvisioningRuleClient) EXPECT() *MockAutoUserProvisioningRuleClient_Expecter {
	return &MockAutoUserProvisioningRuleClient_Expecter{mock: &_m.Mock}
}

// CreateAutoUserProvisioningRule provides a mock function for the type MockAutoUserProvisioningRuleClient
func (_mock *MockAutoUserProvisioningRuleClient) CreateAutoUserProvisioningRule(body *models.CreateAutoUserProvisioningRuleV1Request) (*models.CreateAutoUserProvisioningRuleResponse, *apiutils.APIError) {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CreateAutoUserProvisioningRule")
	}

	var r0 *models.CreateAutoUserProvisioningRuleResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*models.CreateAutoUserProvisioningRuleV1Request) (*models.CreateAutoUserProvisioningRuleResponse, *apiutils.APIError)); ok {
		return returnFunc(body)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.CreateAutoUserProvisioningRuleV1Request) *models.CreateAutoUserProvisioningRuleResponse); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CreateAutoUserProvisioningRuleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.CreateAutoUserProvisioningRuleV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAutoUserProvisioningRuleClient_CreateAutoUserProvisioningRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAutoUserProvisioningRule'
type MockAutoUserProvisioningRuleClient_CreateAutoUserProvisioningRule_Call struct {
	*mock.Call
}

// CreateAutoUserProvisioningRule is a helper method to define mock.On call
//   - body *models.CreateAutoUserProvisioningRuleV1Request
func (_e *MockAutoUserProvisioningRuleClient_Expecter) CreateAutoUserProvisioningRule(body interface{}) *MockAutoUserProvisioningRuleClient_CreateAutoUserProvisioningRule_Call {
	return &MockAutoUserProvisioningRuleClient_CreateAutoUserProvisioningRule_Call{Call: _e.mock.On("CreateAutoUserProvisioningRule", body)}
}

func (_c *MockAutoUserProvisioningRuleClient_CreateAutoUserProvisioningRule_Call) Run(run func(body *models.CreateAutoUserProvisioningRuleV1Request)) *MockAutoUserProvisioningRuleClient_CreateAutoUserProvisioningRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.CreateAutoUserProvisioningRuleV1Request
		if args[0] != nil {
			arg0 = args[0].(*models.CreateAutoUserProvisioningRuleV1Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAutoUserProvisioningRuleClient_CreateAutoUserProvisioningRule_Call) Return(createAutoUserProvisioningRuleResponse *models.CreateAutoUserProvisioningRuleResponse, aPIError *apiutils.APIError) *MockAutoUserProvisioningRuleClient_CreateAutoUserProvisioningRule_Call {
	_c.Call.Return(createAutoUserProvisioningRuleResponse, aPIError)
	return _c
}

func (_c *MockAutoUserProvisioningRuleClient_CreateAutoUserProvisioningRule_Call) RunAndReturn(run func(body *models.CreateAutoUserProvisioningRuleV1Request) (*models.CreateAutoUserProvisioningRuleResponse, *apiutils.APIError)) *MockAutoUserProvisioningRuleClient_CreateAutoUserProvisioningRule_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAutoUserProvisioningRule provides a mock function for the type MockAutoUserProvisioningRuleClient
func (_mock *MockAutoUserProvisioningRuleClient) DeleteAutoUserProvisioningRule(ruleId string) (interface{}, *apiutils.APIError) {
	ret := _mock.Called(ruleId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAutoUserProvisioningRule")
	}

	var r0 interface{}
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string) (interface{}, *apiutils.APIError)); ok {
		return returnFunc(ruleId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(ruleId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = returnFunc(ruleId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAutoUserProvisioningRuleClient_DeleteAutoUserProvisioningRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAutoUserProvisioningRule'
type MockAutoUserProvisioningRuleClient_DeleteAutoUserProvisioningRule_Call struct {
	*mock.Call
}

// DeleteAutoUserProvisioningRule is a helper method to define mock.On call
//   - ruleId string
func (_e *MockAutoUserProvisioningRuleClient_Expecter) DeleteAutoUserProvisioningRule(ruleId interface{}) *MockAutoUserProvisioningRuleClient_DeleteAutoUserProvisioningRule_Call {
	return &MockAutoUserProvisioningRuleClient_DeleteAutoUserProvisioningRule_Call{Call: _e.mock.On("DeleteAutoUserProvisioningRule", ruleId)}
}

func (_c *MockAutoUserProvisioningRuleClient_DeleteAutoUserProvisioningRule_Call) Run(run func(ruleId string)) *MockAutoUserProvisioningRuleClient_DeleteAutoUserProvisioningRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAutoUserProvisioningRuleClient_DeleteAutoUserProvisioningRule_Call) Return(ifaceVal interface{}, aPIError *apiutils.APIError) *MockAutoUserProvisioningRuleClient_DeleteAutoUserProvisioningRule_Call {
	_c.Call.Return(ifaceVal, aPIError)
	return _c
}

func (_c *MockAutoUserProvisioningRuleClient_DeleteAutoUserProvisioningRule_Call) RunAndReturn(run func(ruleId string) (interface{}, *apiutils.APIError)) *MockAutoUserProvisioningRuleClient_DeleteAutoUserProvisioningRule_Call {
	_c.Call.Return(run)
	return _c
}

// ListAutoUserProvisioningRules provides a mock function for the type MockAutoUserProvisioningRuleClient
func (_mock *MockAutoUserProvisioningRuleClient) ListAutoUserProvisioningRules(limit *int64, start *string, filter *string) (*models.ListAutoUserProvisioningRulesResponse, *apiutils.APIError) {
	ret := _mock.Called(limit, start, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListAutoUserProvisioningRules")
	}

	var r0 *models.ListAutoUserProvisioningRulesResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string) (*models.ListAutoUserProvisioningRulesResponse, *apiutils.APIError)); ok {
		return returnFunc(limit, start, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string) *models.ListAutoUserProvisioningRulesResponse); ok {
		r0 = returnFunc(limit, start, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListAutoUserProvisioningRulesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*int64, *string, *string) *apiutils.APIError); ok {
		r1 = returnFunc(limit, start, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAutoUserProvisioningRuleClient_ListAutoUserProvisioningRules_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAutoUserProvisioningRules'
type MockAutoUserProvisioningRuleClient_ListAutoUserProvisioningRules_Call struct {
	*mock.Call
}

// ListAutoUserProvisioningRules is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - filter *string
func (_e *MockAutoUserProvisioningRuleClient_Expecter) ListAutoUserProvisioningRules(limit interface{}, start interface{}, filter interface{}) *MockAutoUserProvisioningRuleClient_ListAutoUserProvisioningRules_Call {
	return &MockAutoUserProvisioningRuleClient_ListAutoUserProvisioningRules_Call{Call: _e.mock.On("ListAutoUserProvisioningRules", limit, start, filter)}
}

func (_c *MockAutoUserProvisioningRuleClient_ListAutoUserProvisioningRules_Call) Run(run func(limit *int64, start *string, filter *string)) *MockAutoUserProvisioningRuleClient_ListAutoUserProvisioningRules_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *int64
		if args[0] != nil {
			arg0 = args[0].(*int64)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAutoUserProvisioningRuleClient_ListAutoUserProvisioningRules_Call) Return(listAutoUserProvisioningRulesResponse *models.ListAutoUserProvisioningRulesResponse, aPIError *apiutils.APIError) *MockAutoUserProvisioningRuleClient_ListAutoUserProvisioningRules_Call {
	_c.Call.Return(listAutoUserProvisioningRulesResponse, aPIError)
	return _c
}

func (_c *MockAutoUserProvisioningRuleClient_ListAutoUserProvisioningRules_Call) RunAndReturn(run func(limit *int64, start *string, filter *string) (*models.ListAutoUserProvisioningRulesResponse, *apiutils.APIError)) *MockAutoUserProvisioningRuleClient_ListAutoUserProvisioningRules_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAutoUserProvisioningRule provides a mock function for the type MockAutoUserProvisioningRuleClient
func (_mock *MockAutoUserProvisioningRuleClient) ReadAutoUserProvisioningRule(ruleId string) (*models.ReadAutoUserProvisioningRuleResponse, *apiutils.APIError) {
	ret := _mock.Called(ruleId)

	if len(ret) == 0 {
		panic("no return value specified for ReadAutoUserProvisioningRule")
	}

	var r0 *models.ReadAutoUserProvisioningRuleResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string) (*models.ReadAutoUserProvisioningRuleResponse, *apiutils.APIError)); ok {
		return returnFunc(ruleId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.ReadAutoUserProvisioningRuleResponse); ok {
		r0 = returnFunc(ruleId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadAutoUserProvisioningRuleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = returnFunc(ruleId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAutoUserProvisioningRuleClient_ReadAutoUserProvisioningRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAutoUserProvisioningRule'
type MockAutoUserProvisioningRuleClient_ReadAutoUserProvisioningRule_Call struct {
	*mock.Call
}

// ReadAutoUserProvisioningRule is a helper method to define mock.On call
//   - ruleId string
func (_e *MockAutoUserProvisioningRuleClient_Expecter) ReadAutoUserProvisioningRule(ruleId interface{}) *MockAutoUserProvisioningRuleClient_ReadAutoUserProvisioningRule_Call {
	return &MockAutoUserProvisioningRuleClient_ReadAutoUserProvisioningRule_Call{Call: _e.mock.On("ReadAutoUserProvisioningRule", ruleId)}
}

func (_c *MockAutoUserProvisioningRuleClient_ReadAutoUserProvisioningRule_Call) Run(run func(ruleId string)) *MockAutoUserProvisioningRuleClient_ReadAutoUserProvisioningRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAutoUserProvisioningRuleClient_ReadAutoUserProvisioningRule_Call) Return(readAutoUserProvisioningRuleResponse *models.ReadAutoUserProvisioningRuleResponse, aPIError *apiutils.APIError) *MockAutoUserProvisioningRuleClient_ReadAutoUserProvisioningRule_Call {
	_c.Call.Return(readAutoUserProvisioningRuleResponse, aPIError)
	return _c
}

func (_c *MockAutoUserProvisioningRuleClient_ReadAutoUserProvisioningRule_Call) RunAndReturn(run func(ruleId string) (*models.ReadAutoUserProvisioningRuleResponse, *apiutils.APIError)) *MockAutoUserProvisioningRuleClient_ReadAutoUserProvisioningRule_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAutoUserProvisioningRule provides a mock function for the type MockAutoUserProvisioningRuleClient
func (_mock *MockAutoUserProvisioningRuleClient) UpdateAutoUserProvisioningRule(ruleId string, body *models.UpdateAutoUserProvisioningRuleV1Request) (*models.UpdateAutoUserProvisioningRuleResponse, *apiutils.APIError) {
	ret := _mock.Called(ruleId, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAutoUserProvisioningRule")
	}

	var r0 *models.UpdateAutoUserProvisioningRuleResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, *models.UpdateAutoUserProvisioningRuleV1Request) (*models.UpdateAutoUserProvisioningRuleResponse, *apiutils.APIError)); ok {
		return returnFunc(ruleId, body)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *models.UpdateAutoUserProvisioningRuleV1Request) *models.UpdateAutoUserProvisioningRuleResponse); ok {
		r0 = returnFunc(ruleId, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UpdateAutoUserProvisioningRuleResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *models.UpdateAutoUserProvisioningRuleV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(ruleId, body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAutoUserProvisioningRuleClient_UpdateAutoUserProvisioningRule_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAutoUserProvisioningRule'
type MockAutoUserProvisioningRuleClient_UpdateAutoUserProvisioningRule_Call struct {
	*mock.Call
}

// UpdateAutoUserProvisioningRule is a helper method to define mock.On call
//   - ruleId string
//   - body *models.UpdateAutoUserProvisioningRuleV1Request
func (_e *MockAutoUserProvisioningRuleClient_Expecter) UpdateAutoUserProvisioningRule(ruleId interface{}, body interface{}) *MockAutoUserProvisioningRuleClient_UpdateAutoUserProvisioningRule_Call {
	return &MockAutoUserProvisioningRuleClient_UpdateAutoUserProvisioningRule_Call{Call: _e.mock.On("UpdateAutoUserProvisioningRule", ruleId, body)}
}

func (_c *MockAutoUserProvisioningRuleClient_UpdateAutoUserProvisioningRule_Call) Run(run func(ruleId string, body *models.UpdateAutoUserProvisioningRuleV1Request)) *MockAutoUserProvisioningRuleClient_UpdateAutoUserProvisioningRule_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *models.UpdateAutoUserProvisioningRuleV1Request
		if args[1] != nil {
			arg1 = args[1].(*models.UpdateAutoUserProvisioningRuleV1Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAutoUserProvisioningRuleClient_UpdateAutoUserProvisioningRule_Call) Return(updateAutoUserProvisioningRuleResponse *models.UpdateAutoUserProvisioningRuleResponse, aPIError *apiutils.APIError) *MockAutoUserProvisioningRuleClient_UpdateAutoUserProvisioningRule_Call {
	_c.Call.Return(updateAutoUserProvisioningRuleResponse, aPIError)
	return _c
}

func (_c *MockAutoUserProvisioningRuleClient_UpdateAutoUserProvisioningRule_Call) RunAndReturn(run func(ruleId string, body *models.UpdateAutoUserProvisioningRuleV1Request) (*models.UpdateAutoUserProvisioningRuleResponse, *apiutils.APIError)) *MockAutoUserProvisioningRuleClient_UpdateAutoUserProvisioningRule_Call {
	_c.Call.Return(run)
	return _c
}
