// Code generated by mockery. DO NOT EDIT.

package sdkclients

import (
	apiutils "github.com/clumio-code/clumio-go-sdk/api_utils"
	mock "github.com/stretchr/testify/mock"

	models "github.com/clumio-code/clumio-go-sdk/models"
)

// MockAWSTemplatesClient is an autogenerated mock type for the AWSTemplatesClient type
type MockAWSTemplatesClient struct {
	mock.Mock
}

type MockAWSTemplatesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAWSTemplatesClient) EXPECT() *MockAWSTemplatesClient_Expecter {
	return &MockAWSTemplatesClient_Expecter{mock: &_m.Mock}
}

// CreateConnectionTemplate provides a mock function with given fields: body
func (_m *MockAWSTemplatesClient) CreateConnectionTemplate(body *models.CreateConnectionTemplateV1Request) (*models.CreateAWSTemplateV2Response, *apiutils.APIError) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnectionTemplate")
	}

	var r0 *models.CreateAWSTemplateV2Response
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(*models.CreateConnectionTemplateV1Request) (*models.CreateAWSTemplateV2Response, *apiutils.APIError)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(*models.CreateConnectionTemplateV1Request) *models.CreateAWSTemplateV2Response); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CreateAWSTemplateV2Response)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.CreateConnectionTemplateV1Request) *apiutils.APIError); ok {
		r1 = rf(body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockAWSTemplatesClient_CreateConnectionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConnectionTemplate'
type MockAWSTemplatesClient_CreateConnectionTemplate_Call struct {
	*mock.Call
}

// CreateConnectionTemplate is a helper method to define mock.On call
//   - body *models.CreateConnectionTemplateV1Request
func (_e *MockAWSTemplatesClient_Expecter) CreateConnectionTemplate(body interface{}) *MockAWSTemplatesClient_CreateConnectionTemplate_Call {
	return &MockAWSTemplatesClient_CreateConnectionTemplate_Call{Call: _e.mock.On("CreateConnectionTemplate", body)}
}

func (_c *MockAWSTemplatesClient_CreateConnectionTemplate_Call) Run(run func(body *models.CreateConnectionTemplateV1Request)) *MockAWSTemplatesClient_CreateConnectionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.CreateConnectionTemplateV1Request))
	})
	return _c
}

func (_c *MockAWSTemplatesClient_CreateConnectionTemplate_Call) Return(_a0 *models.CreateAWSTemplateV2Response, _a1 *apiutils.APIError) *MockAWSTemplatesClient_CreateConnectionTemplate_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAWSTemplatesClient_CreateConnectionTemplate_Call) RunAndReturn(run func(*models.CreateConnectionTemplateV1Request) (*models.CreateAWSTemplateV2Response, *apiutils.APIError)) *MockAWSTemplatesClient_CreateConnectionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ReadConnectionTemplates provides a mock function with no fields
func (_m *MockAWSTemplatesClient) ReadConnectionTemplates() (*models.ReadAWSTemplatesV2Response, *apiutils.APIError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadConnectionTemplates")
	}

	var r0 *models.ReadAWSTemplatesV2Response
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func() (*models.ReadAWSTemplatesV2Response, *apiutils.APIError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.ReadAWSTemplatesV2Response); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadAWSTemplatesV2Response)
		}
	}

	if rf, ok := ret.Get(1).(func() *apiutils.APIError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockAWSTemplatesClient_ReadConnectionTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadConnectionTemplates'
type MockAWSTemplatesClient_ReadConnectionTemplates_Call struct {
	*mock.Call
}

// ReadConnectionTemplates is a helper method to define mock.On call
func (_e *MockAWSTemplatesClient_Expecter) ReadConnectionTemplates() *MockAWSTemplatesClient_ReadConnectionTemplates_Call {
	return &MockAWSTemplatesClient_ReadConnectionTemplates_Call{Call: _e.mock.On("ReadConnectionTemplates")}
}

func (_c *MockAWSTemplatesClient_ReadConnectionTemplates_Call) Run(run func()) *MockAWSTemplatesClient_ReadConnectionTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAWSTemplatesClient_ReadConnectionTemplates_Call) Return(_a0 *models.ReadAWSTemplatesV2Response, _a1 *apiutils.APIError) *MockAWSTemplatesClient_ReadConnectionTemplates_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockAWSTemplatesClient_ReadConnectionTemplates_Call) RunAndReturn(run func() (*models.ReadAWSTemplatesV2Response, *apiutils.APIError)) *MockAWSTemplatesClient_ReadConnectionTemplates_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockAWSTemplatesClient creates a new instance of MockAWSTemplatesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAWSTemplatesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAWSTemplatesClient {
	mock := &MockAWSTemplatesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
