// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAWSTemplatesClient creates a new instance of MockAWSTemplatesClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAWSTemplatesClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAWSTemplatesClient {
	mock := &MockAWSTemplatesClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAWSTemplatesClient is an autogenerated mock type for the AWSTemplatesClient type
type MockAWSTemplatesClient struct {
	mock.Mock
}

type MockAWSTemplatesClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAWSTemplatesClient) EXPECT() *MockAWSTemplatesClient_Expecter {
	return &MockAWSTemplatesClient_Expecter{mock: &_m.Mock}
}

// CreateConnectionTemplate provides a mock function for the type MockAWSTemplatesClient
func (_mock *MockAWSTemplatesClient) CreateConnectionTemplate(returnGroupToken *bool, body *models.CreateConnectionTemplateV1Request) (*models.CreateAWSTemplateV2Response, *apiutils.APIError) {
	ret := _mock.Called(returnGroupToken, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateConnectionTemplate")
	}

	var r0 *models.CreateAWSTemplateV2Response
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*bool, *models.CreateConnectionTemplateV1Request) (*models.CreateAWSTemplateV2Response, *apiutils.APIError)); ok {
		return returnFunc(returnGroupToken, body)
	}
	if returnFunc, ok := ret.Get(0).(func(*bool, *models.CreateConnectionTemplateV1Request) *models.CreateAWSTemplateV2Response); ok {
		r0 = returnFunc(returnGroupToken, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CreateAWSTemplateV2Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*bool, *models.CreateConnectionTemplateV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(returnGroupToken, body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAWSTemplatesClient_CreateConnectionTemplate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateConnectionTemplate'
type MockAWSTemplatesClient_CreateConnectionTemplate_Call struct {
	*mock.Call
}

// CreateConnectionTemplate is a helper method to define mock.On call
//   - returnGroupToken *bool
//   - body *models.CreateConnectionTemplateV1Request
func (_e *MockAWSTemplatesClient_Expecter) CreateConnectionTemplate(returnGroupToken interface{}, body interface{}) *MockAWSTemplatesClient_CreateConnectionTemplate_Call {
	return &MockAWSTemplatesClient_CreateConnectionTemplate_Call{Call: _e.mock.On("CreateConnectionTemplate", returnGroupToken, body)}
}

func (_c *MockAWSTemplatesClient_CreateConnectionTemplate_Call) Run(run func(returnGroupToken *bool, body *models.CreateConnectionTemplateV1Request)) *MockAWSTemplatesClient_CreateConnectionTemplate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *bool
		if args[0] != nil {
			arg0 = args[0].(*bool)
		}
		var arg1 *models.CreateConnectionTemplateV1Request
		if args[1] != nil {
			arg1 = args[1].(*models.CreateConnectionTemplateV1Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAWSTemplatesClient_CreateConnectionTemplate_Call) Return(createAWSTemplateV2Response *models.CreateAWSTemplateV2Response, aPIError *apiutils.APIError) *MockAWSTemplatesClient_CreateConnectionTemplate_Call {
	_c.Call.Return(createAWSTemplateV2Response, aPIError)
	return _c
}

func (_c *MockAWSTemplatesClient_CreateConnectionTemplate_Call) RunAndReturn(run func(returnGroupToken *bool, body *models.CreateConnectionTemplateV1Request) (*models.CreateAWSTemplateV2Response, *apiutils.APIError)) *MockAWSTemplatesClient_CreateConnectionTemplate_Call {
	_c.Call.Return(run)
	return _c
}

// ReadConnectionTemplates provides a mock function for the type MockAWSTemplatesClient
func (_mock *MockAWSTemplatesClient) ReadConnectionTemplates() (*models.ReadAWSTemplatesV2Response, *apiutils.APIError) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadConnectionTemplates")
	}

	var r0 *models.ReadAWSTemplatesV2Response
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func() (*models.ReadAWSTemplatesV2Response, *apiutils.APIError)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *models.ReadAWSTemplatesV2Response); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadAWSTemplatesV2Response)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() *apiutils.APIError); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAWSTemplatesClient_ReadConnectionTemplates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadConnectionTemplates'
type MockAWSTemplatesClient_ReadConnectionTemplates_Call struct {
	*mock.Call
}

// ReadConnectionTemplates is a helper method to define mock.On call
func (_e *MockAWSTemplatesClient_Expecter) ReadConnectionTemplates() *MockAWSTemplatesClient_ReadConnectionTemplates_Call {
	return &MockAWSTemplatesClient_ReadConnectionTemplates_Call{Call: _e.mock.On("ReadConnectionTemplates")}
}

func (_c *MockAWSTemplatesClient_ReadConnectionTemplates_Call) Run(run func()) *MockAWSTemplatesClient_ReadConnectionTemplates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAWSTemplatesClient_ReadConnectionTemplates_Call) Return(readAWSTemplatesV2Response *models.ReadAWSTemplatesV2Response, aPIError *apiutils.APIError) *MockAWSTemplatesClient_ReadConnectionTemplates_Call {
	_c.Call.Return(readAWSTemplatesV2Response, aPIError)
	return _c
}

func (_c *MockAWSTemplatesClient_ReadConnectionTemplates_Call) RunAndReturn(run func() (*models.ReadAWSTemplatesV2Response, *apiutils.APIError)) *MockAWSTemplatesClient_ReadConnectionTemplates_Call {
	_c.Call.Return(run)
	return _c
}
