// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAWSConnectionClient creates a new instance of MockAWSConnectionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAWSConnectionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAWSConnectionClient {
	mock := &MockAWSConnectionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAWSConnectionClient is an autogenerated mock type for the AWSConnectionClient type
type MockAWSConnectionClient struct {
	mock.Mock
}

type MockAWSConnectionClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAWSConnectionClient) EXPECT() *MockAWSConnectionClient_Expecter {
	return &MockAWSConnectionClient_Expecter{mock: &_m.Mock}
}

// CreateAwsConnection provides a mock function for the type MockAWSConnectionClient
func (_mock *MockAWSConnectionClient) CreateAwsConnection(body *models.CreateAwsConnectionV1Request) (*models.CreateAWSConnectionResponse, *apiutils.APIError) {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CreateAwsConnection")
	}

	var r0 *models.CreateAWSConnectionResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*models.CreateAwsConnectionV1Request) (*models.CreateAWSConnectionResponse, *apiutils.APIError)); ok {
		return returnFunc(body)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.CreateAwsConnectionV1Request) *models.CreateAWSConnectionResponse); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CreateAWSConnectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.CreateAwsConnectionV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAWSConnectionClient_CreateAwsConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAwsConnection'
type MockAWSConnectionClient_CreateAwsConnection_Call struct {
	*mock.Call
}

// CreateAwsConnection is a helper method to define mock.On call
//   - body *models.CreateAwsConnectionV1Request
func (_e *MockAWSConnectionClient_Expecter) CreateAwsConnection(body interface{}) *MockAWSConnectionClient_CreateAwsConnection_Call {
	return &MockAWSConnectionClient_CreateAwsConnection_Call{Call: _e.mock.On("CreateAwsConnection", body)}
}

func (_c *MockAWSConnectionClient_CreateAwsConnection_Call) Run(run func(body *models.CreateAwsConnectionV1Request)) *MockAWSConnectionClient_CreateAwsConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.CreateAwsConnectionV1Request
		if args[0] != nil {
			arg0 = args[0].(*models.CreateAwsConnectionV1Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAWSConnectionClient_CreateAwsConnection_Call) Return(createAWSConnectionResponse *models.CreateAWSConnectionResponse, aPIError *apiutils.APIError) *MockAWSConnectionClient_CreateAwsConnection_Call {
	_c.Call.Return(createAWSConnectionResponse, aPIError)
	return _c
}

func (_c *MockAWSConnectionClient_CreateAwsConnection_Call) RunAndReturn(run func(body *models.CreateAwsConnectionV1Request) (*models.CreateAWSConnectionResponse, *apiutils.APIError)) *MockAWSConnectionClient_CreateAwsConnection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAwsConnection provides a mock function for the type MockAWSConnectionClient
func (_mock *MockAWSConnectionClient) DeleteAwsConnection(connectionId string) (interface{}, *apiutils.APIError) {
	ret := _mock.Called(connectionId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAwsConnection")
	}

	var r0 interface{}
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string) (interface{}, *apiutils.APIError)); ok {
		return returnFunc(connectionId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(connectionId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = returnFunc(connectionId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAWSConnectionClient_DeleteAwsConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAwsConnection'
type MockAWSConnectionClient_DeleteAwsConnection_Call struct {
	*mock.Call
}

// DeleteAwsConnection is a helper method to define mock.On call
//   - connectionId string
func (_e *MockAWSConnectionClient_Expecter) DeleteAwsConnection(connectionId interface{}) *MockAWSConnectionClient_DeleteAwsConnection_Call {
	return &MockAWSConnectionClient_DeleteAwsConnection_Call{Call: _e.mock.On("DeleteAwsConnection", connectionId)}
}

func (_c *MockAWSConnectionClient_DeleteAwsConnection_Call) Run(run func(connectionId string)) *MockAWSConnectionClient_DeleteAwsConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAWSConnectionClient_DeleteAwsConnection_Call) Return(ifaceVal interface{}, aPIError *apiutils.APIError) *MockAWSConnectionClient_DeleteAwsConnection_Call {
	_c.Call.Return(ifaceVal, aPIError)
	return _c
}

func (_c *MockAWSConnectionClient_DeleteAwsConnection_Call) RunAndReturn(run func(connectionId string) (interface{}, *apiutils.APIError)) *MockAWSConnectionClient_DeleteAwsConnection_Call {
	_c.Call.Return(run)
	return _c
}

// ListAwsConnections provides a mock function for the type MockAWSConnectionClient
func (_mock *MockAWSConnectionClient) ListAwsConnections(limit *int64, start *string, filter *string) (*models.ListAWSConnectionsResponse, *apiutils.APIError) {
	ret := _mock.Called(limit, start, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListAwsConnections")
	}

	var r0 *models.ListAWSConnectionsResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string) (*models.ListAWSConnectionsResponse, *apiutils.APIError)); ok {
		return returnFunc(limit, start, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string) *models.ListAWSConnectionsResponse); ok {
		r0 = returnFunc(limit, start, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListAWSConnectionsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*int64, *string, *string) *apiutils.APIError); ok {
		r1 = returnFunc(limit, start, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAWSConnectionClient_ListAwsConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAwsConnections'
type MockAWSConnectionClient_ListAwsConnections_Call struct {
	*mock.Call
}

// ListAwsConnections is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - filter *string
func (_e *MockAWSConnectionClient_Expecter) ListAwsConnections(limit interface{}, start interface{}, filter interface{}) *MockAWSConnectionClient_ListAwsConnections_Call {
	return &MockAWSConnectionClient_ListAwsConnections_Call{Call: _e.mock.On("ListAwsConnections", limit, start, filter)}
}

func (_c *MockAWSConnectionClient_ListAwsConnections_Call) Run(run func(limit *int64, start *string, filter *string)) *MockAWSConnectionClient_ListAwsConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *int64
		if args[0] != nil {
			arg0 = args[0].(*int64)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAWSConnectionClient_ListAwsConnections_Call) Return(listAWSConnectionsResponse *models.ListAWSConnectionsResponse, aPIError *apiutils.APIError) *MockAWSConnectionClient_ListAwsConnections_Call {
	_c.Call.Return(listAWSConnectionsResponse, aPIError)
	return _c
}

func (_c *MockAWSConnectionClient_ListAwsConnections_Call) RunAndReturn(run func(limit *int64, start *string, filter *string) (*models.ListAWSConnectionsResponse, *apiutils.APIError)) *MockAWSConnectionClient_ListAwsConnections_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAwsConnection provides a mock function for the type MockAWSConnectionClient
func (_mock *MockAWSConnectionClient) ReadAwsConnection(connectionId string, returnExternalId *string) (*models.ReadAWSConnectionResponse, *apiutils.APIError) {
	ret := _mock.Called(connectionId, returnExternalId)

	if len(ret) == 0 {
		panic("no return value specified for ReadAwsConnection")
	}

	var r0 *models.ReadAWSConnectionResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, *string) (*models.ReadAWSConnectionResponse, *apiutils.APIError)); ok {
		return returnFunc(connectionId, returnExternalId)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *string) *models.ReadAWSConnectionResponse); ok {
		r0 = returnFunc(connectionId, returnExternalId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadAWSConnectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *string) *apiutils.APIError); ok {
		r1 = returnFunc(connectionId, returnExternalId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAWSConnectionClient_ReadAwsConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAwsConnection'
type MockAWSConnectionClient_ReadAwsConnection_Call struct {
	*mock.Call
}

// ReadAwsConnection is a helper method to define mock.On call
//   - connectionId string
//   - returnExternalId *string
func (_e *MockAWSConnectionClient_Expecter) ReadAwsConnection(connectionId interface{}, returnExternalId interface{}) *MockAWSConnectionClient_ReadAwsConnection_Call {
	return &MockAWSConnectionClient_ReadAwsConnection_Call{Call: _e.mock.On("ReadAwsConnection", connectionId, returnExternalId)}
}

func (_c *MockAWSConnectionClient_ReadAwsConnection_Call) Run(run func(connectionId string, returnExternalId *string)) *MockAWSConnectionClient_ReadAwsConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAWSConnectionClient_ReadAwsConnection_Call) Return(readAWSConnectionResponse *models.ReadAWSConnectionResponse, aPIError *apiutils.APIError) *MockAWSConnectionClient_ReadAwsConnection_Call {
	_c.Call.Return(readAWSConnectionResponse, aPIError)
	return _c
}

func (_c *MockAWSConnectionClient_ReadAwsConnection_Call) RunAndReturn(run func(connectionId string, returnExternalId *string) (*models.ReadAWSConnectionResponse, *apiutils.APIError)) *MockAWSConnectionClient_ReadAwsConnection_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAwsConnection provides a mock function for the type MockAWSConnectionClient
func (_mock *MockAWSConnectionClient) UpdateAwsConnection(connectionId string, body models.UpdateAwsConnectionV1Request) (*models.UpdateAWSConnectionResponse, *apiutils.APIError) {
	ret := _mock.Called(connectionId, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAwsConnection")
	}

	var r0 *models.UpdateAWSConnectionResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, models.UpdateAwsConnectionV1Request) (*models.UpdateAWSConnectionResponse, *apiutils.APIError)); ok {
		return returnFunc(connectionId, body)
	}
	if returnFunc, ok := ret.Get(0).(func(string, models.UpdateAwsConnectionV1Request) *models.UpdateAWSConnectionResponse); ok {
		r0 = returnFunc(connectionId, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UpdateAWSConnectionResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, models.UpdateAwsConnectionV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(connectionId, body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockAWSConnectionClient_UpdateAwsConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAwsConnection'
type MockAWSConnectionClient_UpdateAwsConnection_Call struct {
	*mock.Call
}

// UpdateAwsConnection is a helper method to define mock.On call
//   - connectionId string
//   - body models.UpdateAwsConnectionV1Request
func (_e *MockAWSConnectionClient_Expecter) UpdateAwsConnection(connectionId interface{}, body interface{}) *MockAWSConnectionClient_UpdateAwsConnection_Call {
	return &MockAWSConnectionClient_UpdateAwsConnection_Call{Call: _e.mock.On("UpdateAwsConnection", connectionId, body)}
}

func (_c *MockAWSConnectionClient_UpdateAwsConnection_Call) Run(run func(connectionId string, body models.UpdateAwsConnectionV1Request)) *MockAWSConnectionClient_UpdateAwsConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models.UpdateAwsConnectionV1Request
		if args[1] != nil {
			arg1 = args[1].(models.UpdateAwsConnectionV1Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAWSConnectionClient_UpdateAwsConnection_Call) Return(updateAWSConnectionResponse *models.UpdateAWSConnectionResponse, aPIError *apiutils.APIError) *MockAWSConnectionClient_UpdateAwsConnection_Call {
	_c.Call.Return(updateAWSConnectionResponse, aPIError)
	return _c
}

func (_c *MockAWSConnectionClient_UpdateAwsConnection_Call) RunAndReturn(run func(connectionId string, body models.UpdateAwsConnectionV1Request) (*models.UpdateAWSConnectionResponse, *apiutils.APIError)) *MockAWSConnectionClient_UpdateAwsConnection_Call {
	_c.Call.Return(run)
	return _c
}
