// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockBackupDynamoDBTableClient creates a new instance of MockBackupDynamoDBTableClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockBackupDynamoDBTableClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockBackupDynamoDBTableClient {
	mock := &MockBackupDynamoDBTableClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockBackupDynamoDBTableClient is an autogenerated mock type for the BackupDynamoDBTableClient type
type MockBackupDynamoDBTableClient struct {
	mock.Mock
}

type MockBackupDynamoDBTableClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockBackupDynamoDBTableClient) EXPECT() *MockBackupDynamoDBTableClient_Expecter {
	return &MockBackupDynamoDBTableClient_Expecter{mock: &_m.Mock}
}

// CreateBackupAwsDynamodbTable provides a mock function for the type MockBackupDynamoDBTableClient
func (_mock *MockBackupDynamoDBTableClient) CreateBackupAwsDynamodbTable(embed *string, body models.CreateBackupAwsDynamodbTableV1Request) (*models.OnDemandDynamoDBBackupResponse, *apiutils.APIError) {
	ret := _mock.Called(embed, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateBackupAwsDynamodbTable")
	}

	var r0 *models.OnDemandDynamoDBBackupResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*string, models.CreateBackupAwsDynamodbTableV1Request) (*models.OnDemandDynamoDBBackupResponse, *apiutils.APIError)); ok {
		return returnFunc(embed, body)
	}
	if returnFunc, ok := ret.Get(0).(func(*string, models.CreateBackupAwsDynamodbTableV1Request) *models.OnDemandDynamoDBBackupResponse); ok {
		r0 = returnFunc(embed, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.OnDemandDynamoDBBackupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*string, models.CreateBackupAwsDynamodbTableV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(embed, body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockBackupDynamoDBTableClient_CreateBackupAwsDynamodbTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBackupAwsDynamodbTable'
type MockBackupDynamoDBTableClient_CreateBackupAwsDynamodbTable_Call struct {
	*mock.Call
}

// CreateBackupAwsDynamodbTable is a helper method to define mock.On call
//   - embed *string
//   - body models.CreateBackupAwsDynamodbTableV1Request
func (_e *MockBackupDynamoDBTableClient_Expecter) CreateBackupAwsDynamodbTable(embed interface{}, body interface{}) *MockBackupDynamoDBTableClient_CreateBackupAwsDynamodbTable_Call {
	return &MockBackupDynamoDBTableClient_CreateBackupAwsDynamodbTable_Call{Call: _e.mock.On("CreateBackupAwsDynamodbTable", embed, body)}
}

func (_c *MockBackupDynamoDBTableClient_CreateBackupAwsDynamodbTable_Call) Run(run func(embed *string, body models.CreateBackupAwsDynamodbTableV1Request)) *MockBackupDynamoDBTableClient_CreateBackupAwsDynamodbTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *string
		if args[0] != nil {
			arg0 = args[0].(*string)
		}
		var arg1 models.CreateBackupAwsDynamodbTableV1Request
		if args[1] != nil {
			arg1 = args[1].(models.CreateBackupAwsDynamodbTableV1Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockBackupDynamoDBTableClient_CreateBackupAwsDynamodbTable_Call) Return(onDemandDynamoDBBackupResponse *models.OnDemandDynamoDBBackupResponse, aPIError *apiutils.APIError) *MockBackupDynamoDBTableClient_CreateBackupAwsDynamodbTable_Call {
	_c.Call.Return(onDemandDynamoDBBackupResponse, aPIError)
	return _c
}

func (_c *MockBackupDynamoDBTableClient_CreateBackupAwsDynamodbTable_Call) RunAndReturn(run func(embed *string, body models.CreateBackupAwsDynamodbTableV1Request) (*models.OnDemandDynamoDBBackupResponse, *apiutils.APIError)) *MockBackupDynamoDBTableClient_CreateBackupAwsDynamodbTable_Call {
	_c.Call.Return(run)
	return _c
}

// ListBackupAwsDynamodbTables provides a mock function for the type MockBackupDynamoDBTableClient
func (_mock *MockBackupDynamoDBTableClient) ListBackupAwsDynamodbTables(limit *int64, start *string, sort *string, filter *string) (*models.ListDynamoDBTableBackupsResponse, *apiutils.APIError) {
	ret := _mock.Called(limit, start, sort, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListBackupAwsDynamodbTables")
	}

	var r0 *models.ListDynamoDBTableBackupsResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *string) (*models.ListDynamoDBTableBackupsResponse, *apiutils.APIError)); ok {
		return returnFunc(limit, start, sort, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *string) *models.ListDynamoDBTableBackupsResponse); ok {
		r0 = returnFunc(limit, start, sort, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListDynamoDBTableBackupsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*int64, *string, *string, *string) *apiutils.APIError); ok {
		r1 = returnFunc(limit, start, sort, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockBackupDynamoDBTableClient_ListBackupAwsDynamodbTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBackupAwsDynamodbTables'
type MockBackupDynamoDBTableClient_ListBackupAwsDynamodbTables_Call struct {
	*mock.Call
}

// ListBackupAwsDynamodbTables is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - sort *string
//   - filter *string
func (_e *MockBackupDynamoDBTableClient_Expecter) ListBackupAwsDynamodbTables(limit interface{}, start interface{}, sort interface{}, filter interface{}) *MockBackupDynamoDBTableClient_ListBackupAwsDynamodbTables_Call {
	return &MockBackupDynamoDBTableClient_ListBackupAwsDynamodbTables_Call{Call: _e.mock.On("ListBackupAwsDynamodbTables", limit, start, sort, filter)}
}

func (_c *MockBackupDynamoDBTableClient_ListBackupAwsDynamodbTables_Call) Run(run func(limit *int64, start *string, sort *string, filter *string)) *MockBackupDynamoDBTableClient_ListBackupAwsDynamodbTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *int64
		if args[0] != nil {
			arg0 = args[0].(*int64)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockBackupDynamoDBTableClient_ListBackupAwsDynamodbTables_Call) Return(listDynamoDBTableBackupsResponse *models.ListDynamoDBTableBackupsResponse, aPIError *apiutils.APIError) *MockBackupDynamoDBTableClient_ListBackupAwsDynamodbTables_Call {
	_c.Call.Return(listDynamoDBTableBackupsResponse, aPIError)
	return _c
}

func (_c *MockBackupDynamoDBTableClient_ListBackupAwsDynamodbTables_Call) RunAndReturn(run func(limit *int64, start *string, sort *string, filter *string) (*models.ListDynamoDBTableBackupsResponse, *apiutils.APIError)) *MockBackupDynamoDBTableClient_ListBackupAwsDynamodbTables_Call {
	_c.Call.Return(run)
	return _c
}

// ReadBackupAwsDynamodbTable provides a mock function for the type MockBackupDynamoDBTableClient
func (_mock *MockBackupDynamoDBTableClient) ReadBackupAwsDynamodbTable(backupId string) (*models.ReadDynamoDBTableBackupResponse, *apiutils.APIError) {
	ret := _mock.Called(backupId)

	if len(ret) == 0 {
		panic("no return value specified for ReadBackupAwsDynamodbTable")
	}

	var r0 *models.ReadDynamoDBTableBackupResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string) (*models.ReadDynamoDBTableBackupResponse, *apiutils.APIError)); ok {
		return returnFunc(backupId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.ReadDynamoDBTableBackupResponse); ok {
		r0 = returnFunc(backupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadDynamoDBTableBackupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = returnFunc(backupId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockBackupDynamoDBTableClient_ReadBackupAwsDynamodbTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadBackupAwsDynamodbTable'
type MockBackupDynamoDBTableClient_ReadBackupAwsDynamodbTable_Call struct {
	*mock.Call
}

// ReadBackupAwsDynamodbTable is a helper method to define mock.On call
//   - backupId string
func (_e *MockBackupDynamoDBTableClient_Expecter) ReadBackupAwsDynamodbTable(backupId interface{}) *MockBackupDynamoDBTableClient_ReadBackupAwsDynamodbTable_Call {
	return &MockBackupDynamoDBTableClient_ReadBackupAwsDynamodbTable_Call{Call: _e.mock.On("ReadBackupAwsDynamodbTable", backupId)}
}

func (_c *MockBackupDynamoDBTableClient_ReadBackupAwsDynamodbTable_Call) Run(run func(backupId string)) *MockBackupDynamoDBTableClient_ReadBackupAwsDynamodbTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockBackupDynamoDBTableClient_ReadBackupAwsDynamodbTable_Call) Return(readDynamoDBTableBackupResponse *models.ReadDynamoDBTableBackupResponse, aPIError *apiutils.APIError) *MockBackupDynamoDBTableClient_ReadBackupAwsDynamodbTable_Call {
	_c.Call.Return(readDynamoDBTableBackupResponse, aPIError)
	return _c
}

func (_c *MockBackupDynamoDBTableClient_ReadBackupAwsDynamodbTable_Call) RunAndReturn(run func(backupId string) (*models.ReadDynamoDBTableBackupResponse, *apiutils.APIError)) *MockBackupDynamoDBTableClient_ReadBackupAwsDynamodbTable_Call {
	_c.Call.Return(run)
	return _c
}
