// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build unit

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDynamoDBTableClient creates a new instance of MockDynamoDBTableClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDynamoDBTableClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDynamoDBTableClient {
	mock := &MockDynamoDBTableClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDynamoDBTableClient is an autogenerated mock type for the DynamoDBTableClient type
type MockDynamoDBTableClient struct {
	mock.Mock
}

type MockDynamoDBTableClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDynamoDBTableClient) EXPECT() *MockDynamoDBTableClient_Expecter {
	return &MockDynamoDBTableClient_Expecter{mock: &_m.Mock}
}

// ListAwsDynamodbTables provides a mock function for the type MockDynamoDBTableClient
func (_mock *MockDynamoDBTableClient) ListAwsDynamodbTables(limit *int64, start *string, sort *string, filter *string, embed *string, lookbackDays *int64) (*models.ListDynamoDBTableResponse, *apiutils.APIError) {
	ret := _mock.Called(limit, start, sort, filter, embed, lookbackDays)

	if len(ret) == 0 {
		panic("no return value specified for ListAwsDynamodbTables")
	}

	var r0 *models.ListDynamoDBTableResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *string, *string, *int64) (*models.ListDynamoDBTableResponse, *apiutils.APIError)); ok {
		return returnFunc(limit, start, sort, filter, embed, lookbackDays)
	}
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *string, *string, *int64) *models.ListDynamoDBTableResponse); ok {
		r0 = returnFunc(limit, start, sort, filter, embed, lookbackDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListDynamoDBTableResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*int64, *string, *string, *string, *string, *int64) *apiutils.APIError); ok {
		r1 = returnFunc(limit, start, sort, filter, embed, lookbackDays)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockDynamoDBTableClient_ListAwsDynamodbTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAwsDynamodbTables'
type MockDynamoDBTableClient_ListAwsDynamodbTables_Call struct {
	*mock.Call
}

// ListAwsDynamodbTables is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - sort *string
//   - filter *string
//   - embed *string
//   - lookbackDays *int64
func (_e *MockDynamoDBTableClient_Expecter) ListAwsDynamodbTables(limit interface{}, start interface{}, sort interface{}, filter interface{}, embed interface{}, lookbackDays interface{}) *MockDynamoDBTableClient_ListAwsDynamodbTables_Call {
	return &MockDynamoDBTableClient_ListAwsDynamodbTables_Call{Call: _e.mock.On("ListAwsDynamodbTables", limit, start, sort, filter, embed, lookbackDays)}
}

func (_c *MockDynamoDBTableClient_ListAwsDynamodbTables_Call) Run(run func(limit *int64, start *string, sort *string, filter *string, embed *string, lookbackDays *int64)) *MockDynamoDBTableClient_ListAwsDynamodbTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *int64
		if args[0] != nil {
			arg0 = args[0].(*int64)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *string
		if args[4] != nil {
			arg4 = args[4].(*string)
		}
		var arg5 *int64
		if args[5] != nil {
			arg5 = args[5].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockDynamoDBTableClient_ListAwsDynamodbTables_Call) Return(listDynamoDBTableResponse *models.ListDynamoDBTableResponse, aPIError *apiutils.APIError) *MockDynamoDBTableClient_ListAwsDynamodbTables_Call {
	_c.Call.Return(listDynamoDBTableResponse, aPIError)
	return _c
}

func (_c *MockDynamoDBTableClient_ListAwsDynamodbTables_Call) RunAndReturn(run func(limit *int64, start *string, sort *string, filter *string, embed *string, lookbackDays *int64) (*models.ListDynamoDBTableResponse, *apiutils.APIError)) *MockDynamoDBTableClient_ListAwsDynamodbTables_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAwsDynamodbTable provides a mock function for the type MockDynamoDBTableClient
func (_mock *MockDynamoDBTableClient) ReadAwsDynamodbTable(tableId string, lookbackDays *int64, embed *string) (*models.ReadDynamoDBTableResponse, *apiutils.APIError) {
	ret := _mock.Called(tableId, lookbackDays, embed)

	if len(ret) == 0 {
		panic("no return value specified for ReadAwsDynamodbTable")
	}

	var r0 *models.ReadDynamoDBTableResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, *int64, *string) (*models.ReadDynamoDBTableResponse, *apiutils.APIError)); ok {
		return returnFunc(tableId, lookbackDays, embed)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *int64, *string) *models.ReadDynamoDBTableResponse); ok {
		r0 = returnFunc(tableId, lookbackDays, embed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadDynamoDBTableResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *int64, *string) *apiutils.APIError); ok {
		r1 = returnFunc(tableId, lookbackDays, embed)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockDynamoDBTableClient_ReadAwsDynamodbTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAwsDynamodbTable'
type MockDynamoDBTableClient_ReadAwsDynamodbTable_Call struct {
	*mock.Call
}

// ReadAwsDynamodbTable is a helper method to define mock.On call
//   - tableId string
//   - lookbackDays *int64
//   - embed *string
func (_e *MockDynamoDBTableClient_Expecter) ReadAwsDynamodbTable(tableId interface{}, lookbackDays interface{}, embed interface{}) *MockDynamoDBTableClient_ReadAwsDynamodbTable_Call {
	return &MockDynamoDBTableClient_ReadAwsDynamodbTable_Call{Call: _e.mock.On("ReadAwsDynamodbTable", tableId, lookbackDays, embed)}
}

func (_c *MockDynamoDBTableClient_ReadAwsDynamodbTable_Call) Run(run func(tableId string, lookbackDays *int64, embed *string)) *MockDynamoDBTableClient_ReadAwsDynamodbTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockDynamoDBTableClient_ReadAwsDynamodbTable_Call) Return(readDynamoDBTableResponse *models.ReadDynamoDBTableResponse, aPIError *apiutils.APIError) *MockDynamoDBTableClient_ReadAwsDynamodbTable_Call {
	_c.Call.Return(readDynamoDBTableResponse, aPIError)
	return _c
}

func (_c *MockDynamoDBTableClient_ReadAwsDynamodbTable_Call) RunAndReturn(run func(tableId string, lookbackDays *int64, embed *string) (*models.ReadDynamoDBTableResponse, *apiutils.APIError)) *MockDynamoDBTableClient_ReadAwsDynamodbTable_Call {
	_c.Call.Return(run)
	return _c
}
