// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGcpGcsBucketClient creates a new instance of MockGcpGcsBucketClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGcpGcsBucketClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGcpGcsBucketClient {
	mock := &MockGcpGcsBucketClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGcpGcsBucketClient is an autogenerated mock type for the GcpGcsBucketClient type
type MockGcpGcsBucketClient struct {
	mock.Mock
}

type MockGcpGcsBucketClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGcpGcsBucketClient) EXPECT() *MockGcpGcsBucketClient_Expecter {
	return &MockGcpGcsBucketClient_Expecter{mock: &_m.Mock}
}

// ListGcpGcsBuckets provides a mock function for the type MockGcpGcsBucketClient
func (_mock *MockGcpGcsBucketClient) ListGcpGcsBuckets(limit *int64, start *string, filter *string, bucketMatcher *string) (*models.ListGCSBucketsResponse, *apiutils.APIError) {
	ret := _mock.Called(limit, start, filter, bucketMatcher)

	if len(ret) == 0 {
		panic("no return value specified for ListGcpGcsBuckets")
	}

	var r0 *models.ListGCSBucketsResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *string) (*models.ListGCSBucketsResponse, *apiutils.APIError)); ok {
		return returnFunc(limit, start, filter, bucketMatcher)
	}
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *string) *models.ListGCSBucketsResponse); ok {
		r0 = returnFunc(limit, start, filter, bucketMatcher)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListGCSBucketsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*int64, *string, *string, *string) *apiutils.APIError); ok {
		r1 = returnFunc(limit, start, filter, bucketMatcher)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockGcpGcsBucketClient_ListGcpGcsBuckets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGcpGcsBuckets'
type MockGcpGcsBucketClient_ListGcpGcsBuckets_Call struct {
	*mock.Call
}

// ListGcpGcsBuckets is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - filter *string
//   - bucketMatcher *string
func (_e *MockGcpGcsBucketClient_Expecter) ListGcpGcsBuckets(limit interface{}, start interface{}, filter interface{}, bucketMatcher interface{}) *MockGcpGcsBucketClient_ListGcpGcsBuckets_Call {
	return &MockGcpGcsBucketClient_ListGcpGcsBuckets_Call{Call: _e.mock.On("ListGcpGcsBuckets", limit, start, filter, bucketMatcher)}
}

func (_c *MockGcpGcsBucketClient_ListGcpGcsBuckets_Call) Run(run func(limit *int64, start *string, filter *string, bucketMatcher *string)) *MockGcpGcsBucketClient_ListGcpGcsBuckets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *int64
		if args[0] != nil {
			arg0 = args[0].(*int64)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockGcpGcsBucketClient_ListGcpGcsBuckets_Call) Return(listGCSBucketsResponse *models.ListGCSBucketsResponse, aPIError *apiutils.APIError) *MockGcpGcsBucketClient_ListGcpGcsBuckets_Call {
	_c.Call.Return(listGCSBucketsResponse, aPIError)
	return _c
}

func (_c *MockGcpGcsBucketClient_ListGcpGcsBuckets_Call) RunAndReturn(run func(limit *int64, start *string, filter *string, bucketMatcher *string) (*models.ListGCSBucketsResponse, *apiutils.APIError)) *MockGcpGcsBucketClient_ListGcpGcsBuckets_Call {
	_c.Call.Return(run)
	return _c
}

// ReadGcpGcsBucket provides a mock function for the type MockGcpGcsBucketClient
func (_mock *MockGcpGcsBucketClient) ReadGcpGcsBucket(bucketId string) (*models.ReadGCSBucketResponse, *apiutils.APIError) {
	ret := _mock.Called(bucketId)

	if len(ret) == 0 {
		panic("no return value specified for ReadGcpGcsBucket")
	}

	var r0 *models.ReadGCSBucketResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string) (*models.ReadGCSBucketResponse, *apiutils.APIError)); ok {
		return returnFunc(bucketId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.ReadGCSBucketResponse); ok {
		r0 = returnFunc(bucketId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadGCSBucketResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = returnFunc(bucketId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockGcpGcsBucketClient_ReadGcpGcsBucket_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadGcpGcsBucket'
type MockGcpGcsBucketClient_ReadGcpGcsBucket_Call struct {
	*mock.Call
}

// ReadGcpGcsBucket is a helper method to define mock.On call
//   - bucketId string
func (_e *MockGcpGcsBucketClient_Expecter) ReadGcpGcsBucket(bucketId interface{}) *MockGcpGcsBucketClient_ReadGcpGcsBucket_Call {
	return &MockGcpGcsBucketClient_ReadGcpGcsBucket_Call{Call: _e.mock.On("ReadGcpGcsBucket", bucketId)}
}

func (_c *MockGcpGcsBucketClient_ReadGcpGcsBucket_Call) Run(run func(bucketId string)) *MockGcpGcsBucketClient_ReadGcpGcsBucket_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGcpGcsBucketClient_ReadGcpGcsBucket_Call) Return(readGCSBucketResponse *models.ReadGCSBucketResponse, aPIError *apiutils.APIError) *MockGcpGcsBucketClient_ReadGcpGcsBucket_Call {
	_c.Call.Return(readGCSBucketResponse, aPIError)
	return _c
}

func (_c *MockGcpGcsBucketClient_ReadGcpGcsBucket_Call) RunAndReturn(run func(bucketId string) (*models.ReadGCSBucketResponse, *apiutils.APIError)) *MockGcpGcsBucketClient_ReadGcpGcsBucket_Call {
	_c.Call.Return(run)
	return _c
}
