// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build unit

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockGcpProtectionGroupClient creates a new instance of MockGcpProtectionGroupClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGcpProtectionGroupClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGcpProtectionGroupClient {
	mock := &MockGcpProtectionGroupClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockGcpProtectionGroupClient is an autogenerated mock type for the GcpProtectionGroupClient type
type MockGcpProtectionGroupClient struct {
	mock.Mock
}

type MockGcpProtectionGroupClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGcpProtectionGroupClient) EXPECT() *MockGcpProtectionGroupClient_Expecter {
	return &MockGcpProtectionGroupClient_Expecter{mock: &_m.Mock}
}

// CreateGcpProtectionGroup provides a mock function for the type MockGcpProtectionGroupClient
func (_mock *MockGcpProtectionGroupClient) CreateGcpProtectionGroup(body models.CreateGcpProtectionGroupV1Request) (*models.CreateGCPProtectionGroupResponse, *apiutils.APIError) {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CreateGcpProtectionGroup")
	}

	var r0 *models.CreateGCPProtectionGroupResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(models.CreateGcpProtectionGroupV1Request) (*models.CreateGCPProtectionGroupResponse, *apiutils.APIError)); ok {
		return returnFunc(body)
	}
	if returnFunc, ok := ret.Get(0).(func(models.CreateGcpProtectionGroupV1Request) *models.CreateGCPProtectionGroupResponse); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CreateGCPProtectionGroupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(models.CreateGcpProtectionGroupV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockGcpProtectionGroupClient_CreateGcpProtectionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGcpProtectionGroup'
type MockGcpProtectionGroupClient_CreateGcpProtectionGroup_Call struct {
	*mock.Call
}

// CreateGcpProtectionGroup is a helper method to define mock.On call
//   - body models.CreateGcpProtectionGroupV1Request
func (_e *MockGcpProtectionGroupClient_Expecter) CreateGcpProtectionGroup(body interface{}) *MockGcpProtectionGroupClient_CreateGcpProtectionGroup_Call {
	return &MockGcpProtectionGroupClient_CreateGcpProtectionGroup_Call{Call: _e.mock.On("CreateGcpProtectionGroup", body)}
}

func (_c *MockGcpProtectionGroupClient_CreateGcpProtectionGroup_Call) Run(run func(body models.CreateGcpProtectionGroupV1Request)) *MockGcpProtectionGroupClient_CreateGcpProtectionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 models.CreateGcpProtectionGroupV1Request
		if args[0] != nil {
			arg0 = args[0].(models.CreateGcpProtectionGroupV1Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGcpProtectionGroupClient_CreateGcpProtectionGroup_Call) Return(createGCPProtectionGroupResponse *models.CreateGCPProtectionGroupResponse, aPIError *apiutils.APIError) *MockGcpProtectionGroupClient_CreateGcpProtectionGroup_Call {
	_c.Call.Return(createGCPProtectionGroupResponse, aPIError)
	return _c
}

func (_c *MockGcpProtectionGroupClient_CreateGcpProtectionGroup_Call) RunAndReturn(run func(body models.CreateGcpProtectionGroupV1Request) (*models.CreateGCPProtectionGroupResponse, *apiutils.APIError)) *MockGcpProtectionGroupClient_CreateGcpProtectionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGcpProtectionGroup provides a mock function for the type MockGcpProtectionGroupClient
func (_mock *MockGcpProtectionGroupClient) DeleteGcpProtectionGroup(protectionGroupId string) (interface{}, *apiutils.APIError) {
	ret := _mock.Called(protectionGroupId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGcpProtectionGroup")
	}

	var r0 interface{}
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string) (interface{}, *apiutils.APIError)); ok {
		return returnFunc(protectionGroupId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(protectionGroupId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = returnFunc(protectionGroupId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockGcpProtectionGroupClient_DeleteGcpProtectionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGcpProtectionGroup'
type MockGcpProtectionGroupClient_DeleteGcpProtectionGroup_Call struct {
	*mock.Call
}

// DeleteGcpProtectionGroup is a helper method to define mock.On call
//   - protectionGroupId string
func (_e *MockGcpProtectionGroupClient_Expecter) DeleteGcpProtectionGroup(protectionGroupId interface{}) *MockGcpProtectionGroupClient_DeleteGcpProtectionGroup_Call {
	return &MockGcpProtectionGroupClient_DeleteGcpProtectionGroup_Call{Call: _e.mock.On("DeleteGcpProtectionGroup", protectionGroupId)}
}

func (_c *MockGcpProtectionGroupClient_DeleteGcpProtectionGroup_Call) Run(run func(protectionGroupId string)) *MockGcpProtectionGroupClient_DeleteGcpProtectionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockGcpProtectionGroupClient_DeleteGcpProtectionGroup_Call) Return(ifaceVal interface{}, aPIError *apiutils.APIError) *MockGcpProtectionGroupClient_DeleteGcpProtectionGroup_Call {
	_c.Call.Return(ifaceVal, aPIError)
	return _c
}

func (_c *MockGcpProtectionGroupClient_DeleteGcpProtectionGroup_Call) RunAndReturn(run func(protectionGroupId string) (interface{}, *apiutils.APIError)) *MockGcpProtectionGroupClient_DeleteGcpProtectionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// ListGcpProtectionGroups provides a mock function for the type MockGcpProtectionGroupClient
func (_mock *MockGcpProtectionGroupClient) ListGcpProtectionGroups(limit *int64, start *string, filter *string, bucketUuidDetail *string, lookbackDays *int64) (*models.ListGCPProtectionGroupsResponse, *apiutils.APIError) {
	ret := _mock.Called(limit, start, filter, bucketUuidDetail, lookbackDays)

	if len(ret) == 0 {
		panic("no return value specified for ListGcpProtectionGroups")
	}

	var r0 *models.ListGCPProtectionGroupsResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *string, *int64) (*models.ListGCPProtectionGroupsResponse, *apiutils.APIError)); ok {
		return returnFunc(limit, start, filter, bucketUuidDetail, lookbackDays)
	}
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *string, *int64) *models.ListGCPProtectionGroupsResponse); ok {
		r0 = returnFunc(limit, start, filter, bucketUuidDetail, lookbackDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListGCPProtectionGroupsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*int64, *string, *string, *string, *int64) *apiutils.APIError); ok {
		r1 = returnFunc(limit, start, filter, bucketUuidDetail, lookbackDays)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockGcpProtectionGroupClient_ListGcpProtectionGroups_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGcpProtectionGroups'
type MockGcpProtectionGroupClient_ListGcpProtectionGroups_Call struct {
	*mock.Call
}

// ListGcpProtectionGroups is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - filter *string
//   - bucketUuidDetail *string
//   - lookbackDays *int64
func (_e *MockGcpProtectionGroupClient_Expecter) ListGcpProtectionGroups(limit interface{}, start interface{}, filter interface{}, bucketUuidDetail interface{}, lookbackDays interface{}) *MockGcpProtectionGroupClient_ListGcpProtectionGroups_Call {
	return &MockGcpProtectionGroupClient_ListGcpProtectionGroups_Call{Call: _e.mock.On("ListGcpProtectionGroups", limit, start, filter, bucketUuidDetail, lookbackDays)}
}

func (_c *MockGcpProtectionGroupClient_ListGcpProtectionGroups_Call) Run(run func(limit *int64, start *string, filter *string, bucketUuidDetail *string, lookbackDays *int64)) *MockGcpProtectionGroupClient_ListGcpProtectionGroups_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *int64
		if args[0] != nil {
			arg0 = args[0].(*int64)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockGcpProtectionGroupClient_ListGcpProtectionGroups_Call) Return(listGCPProtectionGroupsResponse *models.ListGCPProtectionGroupsResponse, aPIError *apiutils.APIError) *MockGcpProtectionGroupClient_ListGcpProtectionGroups_Call {
	_c.Call.Return(listGCPProtectionGroupsResponse, aPIError)
	return _c
}

func (_c *MockGcpProtectionGroupClient_ListGcpProtectionGroups_Call) RunAndReturn(run func(limit *int64, start *string, filter *string, bucketUuidDetail *string, lookbackDays *int64) (*models.ListGCPProtectionGroupsResponse, *apiutils.APIError)) *MockGcpProtectionGroupClient_ListGcpProtectionGroups_Call {
	_c.Call.Return(run)
	return _c
}

// ReadGcpProtectionGroup provides a mock function for the type MockGcpProtectionGroupClient
func (_mock *MockGcpProtectionGroupClient) ReadGcpProtectionGroup(protectionGroupId string, lookbackDays *int64) (*models.ReadGCPProtectionGroupResponse, *apiutils.APIError) {
	ret := _mock.Called(protectionGroupId, lookbackDays)

	if len(ret) == 0 {
		panic("no return value specified for ReadGcpProtectionGroup")
	}

	var r0 *models.ReadGCPProtectionGroupResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, *int64) (*models.ReadGCPProtectionGroupResponse, *apiutils.APIError)); ok {
		return returnFunc(protectionGroupId, lookbackDays)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *int64) *models.ReadGCPProtectionGroupResponse); ok {
		r0 = returnFunc(protectionGroupId, lookbackDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadGCPProtectionGroupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *int64) *apiutils.APIError); ok {
		r1 = returnFunc(protectionGroupId, lookbackDays)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockGcpProtectionGroupClient_ReadGcpProtectionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadGcpProtectionGroup'
type MockGcpProtectionGroupClient_ReadGcpProtectionGroup_Call struct {
	*mock.Call
}

// ReadGcpProtectionGroup is a helper method to define mock.On call
//   - protectionGroupId string
//   - lookbackDays *int64
func (_e *MockGcpProtectionGroupClient_Expecter) ReadGcpProtectionGroup(protectionGroupId interface{}, lookbackDays interface{}) *MockGcpProtectionGroupClient_ReadGcpProtectionGroup_Call {
	return &MockGcpProtectionGroupClient_ReadGcpProtectionGroup_Call{Call: _e.mock.On("ReadGcpProtectionGroup", protectionGroupId, lookbackDays)}
}

func (_c *MockGcpProtectionGroupClient_ReadGcpProtectionGroup_Call) Run(run func(protectionGroupId string, lookbackDays *int64)) *MockGcpProtectionGroupClient_ReadGcpProtectionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGcpProtectionGroupClient_ReadGcpProtectionGroup_Call) Return(readGCPProtectionGroupResponse *models.ReadGCPProtectionGroupResponse, aPIError *apiutils.APIError) *MockGcpProtectionGroupClient_ReadGcpProtectionGroup_Call {
	_c.Call.Return(readGCPProtectionGroupResponse, aPIError)
	return _c
}

func (_c *MockGcpProtectionGroupClient_ReadGcpProtectionGroup_Call) RunAndReturn(run func(protectionGroupId string, lookbackDays *int64) (*models.ReadGCPProtectionGroupResponse, *apiutils.APIError)) *MockGcpProtectionGroupClient_ReadGcpProtectionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGcpProtectionGroup provides a mock function for the type MockGcpProtectionGroupClient
func (_mock *MockGcpProtectionGroupClient) UpdateGcpProtectionGroup(protectionGroupId string, body models.UpdateGcpProtectionGroupV1Request) (*models.UpdateGCPProtectionGroupResponse, *apiutils.APIError) {
	ret := _mock.Called(protectionGroupId, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGcpProtectionGroup")
	}

	var r0 *models.UpdateGCPProtectionGroupResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, models.UpdateGcpProtectionGroupV1Request) (*models.UpdateGCPProtectionGroupResponse, *apiutils.APIError)); ok {
		return returnFunc(protectionGroupId, body)
	}
	if returnFunc, ok := ret.Get(0).(func(string, models.UpdateGcpProtectionGroupV1Request) *models.UpdateGCPProtectionGroupResponse); ok {
		r0 = returnFunc(protectionGroupId, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UpdateGCPProtectionGroupResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, models.UpdateGcpProtectionGroupV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(protectionGroupId, body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockGcpProtectionGroupClient_UpdateGcpProtectionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGcpProtectionGroup'
type MockGcpProtectionGroupClient_UpdateGcpProtectionGroup_Call struct {
	*mock.Call
}

// UpdateGcpProtectionGroup is a helper method to define mock.On call
//   - protectionGroupId string
//   - body models.UpdateGcpProtectionGroupV1Request
func (_e *MockGcpProtectionGroupClient_Expecter) UpdateGcpProtectionGroup(protectionGroupId interface{}, body interface{}) *MockGcpProtectionGroupClient_UpdateGcpProtectionGroup_Call {
	return &MockGcpProtectionGroupClient_UpdateGcpProtectionGroup_Call{Call: _e.mock.On("UpdateGcpProtectionGroup", protectionGroupId, body)}
}

func (_c *MockGcpProtectionGroupClient_UpdateGcpProtectionGroup_Call) Run(run func(protectionGroupId string, body models.UpdateGcpProtectionGroupV1Request)) *MockGcpProtectionGroupClient_UpdateGcpProtectionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 models.UpdateGcpProtectionGroupV1Request
		if args[1] != nil {
			arg1 = args[1].(models.UpdateGcpProtectionGroupV1Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockGcpProtectionGroupClient_UpdateGcpProtectionGroup_Call) Return(updateGCPProtectionGroupResponse *models.UpdateGCPProtectionGroupResponse, aPIError *apiutils.APIError) *MockGcpProtectionGroupClient_UpdateGcpProtectionGroup_Call {
	_c.Call.Return(updateGCPProtectionGroupResponse, aPIError)
	return _c
}

func (_c *MockGcpProtectionGroupClient_UpdateGcpProtectionGroup_Call) RunAndReturn(run func(protectionGroupId string, body models.UpdateGcpProtectionGroupV1Request) (*models.UpdateGCPProtectionGroupResponse, *apiutils.APIError)) *MockGcpProtectionGroupClient_UpdateGcpProtectionGroup_Call {
	_c.Call.Return(run)
	return _c
}
