// Code generated by mockery. DO NOT EDIT.

package sdkclients

import (
	apiutils "github.com/clumio-code/clumio-go-sdk/api_utils"
	mock "github.com/stretchr/testify/mock"

	models "github.com/clumio-code/clumio-go-sdk/models"
)

// MockGcpConnectionClient is an autogenerated mock type for the GcpConnectionClient type
type MockGcpConnectionClient struct {
	mock.Mock
}

type MockGcpConnectionClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGcpConnectionClient) EXPECT() *MockGcpConnectionClient_Expecter {
	return &MockGcpConnectionClient_Expecter{mock: &_m.Mock}
}

// CreateGcpConnection provides a mock function with given fields: body
func (_m *MockGcpConnectionClient) CreateGcpConnection(body *models.CreateGcpConnectionV1Request) (*models.CreateGCPConnectionResponse, *apiutils.APIError) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CreateGcpConnection")
	}

	var r0 *models.CreateGCPConnectionResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(*models.CreateGcpConnectionV1Request) (*models.CreateGCPConnectionResponse, *apiutils.APIError)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(*models.CreateGcpConnectionV1Request) *models.CreateGCPConnectionResponse); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CreateGCPConnectionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.CreateGcpConnectionV1Request) *apiutils.APIError); ok {
		r1 = rf(body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockGcpConnectionClient_CreateGcpConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateGcpConnection'
type MockGcpConnectionClient_CreateGcpConnection_Call struct {
	*mock.Call
}

// CreateGcpConnection is a helper method to define mock.On call
//   - body *models.CreateGcpConnectionV1Request
func (_e *MockGcpConnectionClient_Expecter) CreateGcpConnection(body interface{}) *MockGcpConnectionClient_CreateGcpConnection_Call {
	return &MockGcpConnectionClient_CreateGcpConnection_Call{Call: _e.mock.On("CreateGcpConnection", body)}
}

func (_c *MockGcpConnectionClient_CreateGcpConnection_Call) Run(run func(body *models.CreateGcpConnectionV1Request)) *MockGcpConnectionClient_CreateGcpConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.CreateGcpConnectionV1Request))
	})
	return _c
}

func (_c *MockGcpConnectionClient_CreateGcpConnection_Call) Return(_a0 *models.CreateGCPConnectionResponse, _a1 *apiutils.APIError) *MockGcpConnectionClient_CreateGcpConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGcpConnectionClient_CreateGcpConnection_Call) RunAndReturn(run func(*models.CreateGcpConnectionV1Request) (*models.CreateGCPConnectionResponse, *apiutils.APIError)) *MockGcpConnectionClient_CreateGcpConnection_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteGcpConnection provides a mock function with given fields: projectId
func (_m *MockGcpConnectionClient) DeleteGcpConnection(projectId string) (interface{}, *apiutils.APIError) {
	ret := _m.Called(projectId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteGcpConnection")
	}

	var r0 interface{}
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(string) (interface{}, *apiutils.APIError)); ok {
		return rf(projectId)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(projectId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = rf(projectId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockGcpConnectionClient_DeleteGcpConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteGcpConnection'
type MockGcpConnectionClient_DeleteGcpConnection_Call struct {
	*mock.Call
}

// DeleteGcpConnection is a helper method to define mock.On call
//   - projectId string
func (_e *MockGcpConnectionClient_Expecter) DeleteGcpConnection(projectId interface{}) *MockGcpConnectionClient_DeleteGcpConnection_Call {
	return &MockGcpConnectionClient_DeleteGcpConnection_Call{Call: _e.mock.On("DeleteGcpConnection", projectId)}
}

func (_c *MockGcpConnectionClient_DeleteGcpConnection_Call) Run(run func(projectId string)) *MockGcpConnectionClient_DeleteGcpConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGcpConnectionClient_DeleteGcpConnection_Call) Return(_a0 interface{}, _a1 *apiutils.APIError) *MockGcpConnectionClient_DeleteGcpConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGcpConnectionClient_DeleteGcpConnection_Call) RunAndReturn(run func(string) (interface{}, *apiutils.APIError)) *MockGcpConnectionClient_DeleteGcpConnection_Call {
	_c.Call.Return(run)
	return _c
}

// ListGcpConnections provides a mock function with given fields: limit, start, filter
func (_m *MockGcpConnectionClient) ListGcpConnections(limit *int64, start *string, filter *string) (*models.ListGCPConnectionsResponse, *apiutils.APIError) {
	ret := _m.Called(limit, start, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListGcpConnections")
	}

	var r0 *models.ListGCPConnectionsResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(*int64, *string, *string) (*models.ListGCPConnectionsResponse, *apiutils.APIError)); ok {
		return rf(limit, start, filter)
	}
	if rf, ok := ret.Get(0).(func(*int64, *string, *string) *models.ListGCPConnectionsResponse); ok {
		r0 = rf(limit, start, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListGCPConnectionsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*int64, *string, *string) *apiutils.APIError); ok {
		r1 = rf(limit, start, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockGcpConnectionClient_ListGcpConnections_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListGcpConnections'
type MockGcpConnectionClient_ListGcpConnections_Call struct {
	*mock.Call
}

// ListGcpConnections is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - filter *string
func (_e *MockGcpConnectionClient_Expecter) ListGcpConnections(limit interface{}, start interface{}, filter interface{}) *MockGcpConnectionClient_ListGcpConnections_Call {
	return &MockGcpConnectionClient_ListGcpConnections_Call{Call: _e.mock.On("ListGcpConnections", limit, start, filter)}
}

func (_c *MockGcpConnectionClient_ListGcpConnections_Call) Run(run func(limit *int64, start *string, filter *string)) *MockGcpConnectionClient_ListGcpConnections_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*int64), args[1].(*string), args[2].(*string))
	})
	return _c
}

func (_c *MockGcpConnectionClient_ListGcpConnections_Call) Return(_a0 *models.ListGCPConnectionsResponse, _a1 *apiutils.APIError) *MockGcpConnectionClient_ListGcpConnections_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGcpConnectionClient_ListGcpConnections_Call) RunAndReturn(run func(*int64, *string, *string) (*models.ListGCPConnectionsResponse, *apiutils.APIError)) *MockGcpConnectionClient_ListGcpConnections_Call {
	_c.Call.Return(run)
	return _c
}

// PostProcessGcpConnection provides a mock function with given fields: body
func (_m *MockGcpConnectionClient) PostProcessGcpConnection(body *models.PostProcessGcpConnectionV1Request) (interface{}, *apiutils.APIError) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for PostProcessGcpConnection")
	}

	var r0 interface{}
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(*models.PostProcessGcpConnectionV1Request) (interface{}, *apiutils.APIError)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(*models.PostProcessGcpConnectionV1Request) interface{}); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(*models.PostProcessGcpConnectionV1Request) *apiutils.APIError); ok {
		r1 = rf(body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockGcpConnectionClient_PostProcessGcpConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostProcessGcpConnection'
type MockGcpConnectionClient_PostProcessGcpConnection_Call struct {
	*mock.Call
}

// PostProcessGcpConnection is a helper method to define mock.On call
//   - body *models.PostProcessGcpConnectionV1Request
func (_e *MockGcpConnectionClient_Expecter) PostProcessGcpConnection(body interface{}) *MockGcpConnectionClient_PostProcessGcpConnection_Call {
	return &MockGcpConnectionClient_PostProcessGcpConnection_Call{Call: _e.mock.On("PostProcessGcpConnection", body)}
}

func (_c *MockGcpConnectionClient_PostProcessGcpConnection_Call) Run(run func(body *models.PostProcessGcpConnectionV1Request)) *MockGcpConnectionClient_PostProcessGcpConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.PostProcessGcpConnectionV1Request))
	})
	return _c
}

func (_c *MockGcpConnectionClient_PostProcessGcpConnection_Call) Return(_a0 interface{}, _a1 *apiutils.APIError) *MockGcpConnectionClient_PostProcessGcpConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGcpConnectionClient_PostProcessGcpConnection_Call) RunAndReturn(run func(*models.PostProcessGcpConnectionV1Request) (interface{}, *apiutils.APIError)) *MockGcpConnectionClient_PostProcessGcpConnection_Call {
	_c.Call.Return(run)
	return _c
}

// ReadGcpConnection provides a mock function with given fields: projectId
func (_m *MockGcpConnectionClient) ReadGcpConnection(projectId string) (*models.ReadGCPConnectionResponse, *apiutils.APIError) {
	ret := _m.Called(projectId)

	if len(ret) == 0 {
		panic("no return value specified for ReadGcpConnection")
	}

	var r0 *models.ReadGCPConnectionResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(string) (*models.ReadGCPConnectionResponse, *apiutils.APIError)); ok {
		return rf(projectId)
	}
	if rf, ok := ret.Get(0).(func(string) *models.ReadGCPConnectionResponse); ok {
		r0 = rf(projectId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadGCPConnectionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = rf(projectId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockGcpConnectionClient_ReadGcpConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadGcpConnection'
type MockGcpConnectionClient_ReadGcpConnection_Call struct {
	*mock.Call
}

// ReadGcpConnection is a helper method to define mock.On call
//   - projectId string
func (_e *MockGcpConnectionClient_Expecter) ReadGcpConnection(projectId interface{}) *MockGcpConnectionClient_ReadGcpConnection_Call {
	return &MockGcpConnectionClient_ReadGcpConnection_Call{Call: _e.mock.On("ReadGcpConnection", projectId)}
}

func (_c *MockGcpConnectionClient_ReadGcpConnection_Call) Run(run func(projectId string)) *MockGcpConnectionClient_ReadGcpConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockGcpConnectionClient_ReadGcpConnection_Call) Return(_a0 *models.ReadGCPConnectionResponse, _a1 *apiutils.APIError) *MockGcpConnectionClient_ReadGcpConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGcpConnectionClient_ReadGcpConnection_Call) RunAndReturn(run func(string) (*models.ReadGCPConnectionResponse, *apiutils.APIError)) *MockGcpConnectionClient_ReadGcpConnection_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGcpConnection provides a mock function with given fields: projectId, body
func (_m *MockGcpConnectionClient) UpdateGcpConnection(projectId string, body *models.UpdateGcpConnectionV1Request) (*models.UpdateGCPConnectionResponse, *apiutils.APIError) {
	ret := _m.Called(projectId, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGcpConnection")
	}

	var r0 *models.UpdateGCPConnectionResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(string, *models.UpdateGcpConnectionV1Request) (*models.UpdateGCPConnectionResponse, *apiutils.APIError)); ok {
		return rf(projectId, body)
	}
	if rf, ok := ret.Get(0).(func(string, *models.UpdateGcpConnectionV1Request) *models.UpdateGCPConnectionResponse); ok {
		r0 = rf(projectId, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UpdateGCPConnectionResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *models.UpdateGcpConnectionV1Request) *apiutils.APIError); ok {
		r1 = rf(projectId, body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockGcpConnectionClient_UpdateGcpConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGcpConnection'
type MockGcpConnectionClient_UpdateGcpConnection_Call struct {
	*mock.Call
}

// UpdateGcpConnection is a helper method to define mock.On call
//   - projectId string
//   - body *models.UpdateGcpConnectionV1Request
func (_e *MockGcpConnectionClient_Expecter) UpdateGcpConnection(projectId interface{}, body interface{}) *MockGcpConnectionClient_UpdateGcpConnection_Call {
	return &MockGcpConnectionClient_UpdateGcpConnection_Call{Call: _e.mock.On("UpdateGcpConnection", projectId, body)}
}

func (_c *MockGcpConnectionClient_UpdateGcpConnection_Call) Run(run func(projectId string, body *models.UpdateGcpConnectionV1Request)) *MockGcpConnectionClient_UpdateGcpConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*models.UpdateGcpConnectionV1Request))
	})
	return _c
}

func (_c *MockGcpConnectionClient_UpdateGcpConnection_Call) Return(_a0 *models.UpdateGCPConnectionResponse, _a1 *apiutils.APIError) *MockGcpConnectionClient_UpdateGcpConnection_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGcpConnectionClient_UpdateGcpConnection_Call) RunAndReturn(run func(string, *models.UpdateGcpConnectionV1Request) (*models.UpdateGCPConnectionResponse, *apiutils.APIError)) *MockGcpConnectionClient_UpdateGcpConnection_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGcpConnectionClient creates a new instance of MockGcpConnectionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGcpConnectionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGcpConnectionClient {
	mock := &MockGcpConnectionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
