// Code generated by mockery. DO NOT EDIT.

package sdkclients

import (
	apiutils "github.com/clumio-code/clumio-go-sdk/api_utils"
	mock "github.com/stretchr/testify/mock"

	models "github.com/clumio-code/clumio-go-sdk/models"
)

// MockGeneralSettingsClient is an autogenerated mock type for the GeneralSettingsClient type
type MockGeneralSettingsClient struct {
	mock.Mock
}

type MockGeneralSettingsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockGeneralSettingsClient) EXPECT() *MockGeneralSettingsClient_Expecter {
	return &MockGeneralSettingsClient_Expecter{mock: &_m.Mock}
}

// ReadGeneralSettings provides a mock function with no fields
func (_m *MockGeneralSettingsClient) ReadGeneralSettings() (*models.ReadGeneralSettingsResponseV2, *apiutils.APIError) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadGeneralSettings")
	}

	var r0 *models.ReadGeneralSettingsResponseV2
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func() (*models.ReadGeneralSettingsResponseV2, *apiutils.APIError)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.ReadGeneralSettingsResponseV2); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadGeneralSettingsResponseV2)
		}
	}

	if rf, ok := ret.Get(1).(func() *apiutils.APIError); ok {
		r1 = rf()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockGeneralSettingsClient_ReadGeneralSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadGeneralSettings'
type MockGeneralSettingsClient_ReadGeneralSettings_Call struct {
	*mock.Call
}

// ReadGeneralSettings is a helper method to define mock.On call
func (_e *MockGeneralSettingsClient_Expecter) ReadGeneralSettings() *MockGeneralSettingsClient_ReadGeneralSettings_Call {
	return &MockGeneralSettingsClient_ReadGeneralSettings_Call{Call: _e.mock.On("ReadGeneralSettings")}
}

func (_c *MockGeneralSettingsClient_ReadGeneralSettings_Call) Run(run func()) *MockGeneralSettingsClient_ReadGeneralSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockGeneralSettingsClient_ReadGeneralSettings_Call) Return(_a0 *models.ReadGeneralSettingsResponseV2, _a1 *apiutils.APIError) *MockGeneralSettingsClient_ReadGeneralSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGeneralSettingsClient_ReadGeneralSettings_Call) RunAndReturn(run func() (*models.ReadGeneralSettingsResponseV2, *apiutils.APIError)) *MockGeneralSettingsClient_ReadGeneralSettings_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateGeneralSettings provides a mock function with given fields: body
func (_m *MockGeneralSettingsClient) UpdateGeneralSettings(body *models.UpdateGeneralSettingsV2Request) (*models.PatchGeneralSettingsResponseV2, *apiutils.APIError) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateGeneralSettings")
	}

	var r0 *models.PatchGeneralSettingsResponseV2
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(*models.UpdateGeneralSettingsV2Request) (*models.PatchGeneralSettingsResponseV2, *apiutils.APIError)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(*models.UpdateGeneralSettingsV2Request) *models.PatchGeneralSettingsResponseV2); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PatchGeneralSettingsResponseV2)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.UpdateGeneralSettingsV2Request) *apiutils.APIError); ok {
		r1 = rf(body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockGeneralSettingsClient_UpdateGeneralSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateGeneralSettings'
type MockGeneralSettingsClient_UpdateGeneralSettings_Call struct {
	*mock.Call
}

// UpdateGeneralSettings is a helper method to define mock.On call
//   - body *models.UpdateGeneralSettingsV2Request
func (_e *MockGeneralSettingsClient_Expecter) UpdateGeneralSettings(body interface{}) *MockGeneralSettingsClient_UpdateGeneralSettings_Call {
	return &MockGeneralSettingsClient_UpdateGeneralSettings_Call{Call: _e.mock.On("UpdateGeneralSettings", body)}
}

func (_c *MockGeneralSettingsClient_UpdateGeneralSettings_Call) Run(run func(body *models.UpdateGeneralSettingsV2Request)) *MockGeneralSettingsClient_UpdateGeneralSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.UpdateGeneralSettingsV2Request))
	})
	return _c
}

func (_c *MockGeneralSettingsClient_UpdateGeneralSettings_Call) Return(_a0 *models.PatchGeneralSettingsResponseV2, _a1 *apiutils.APIError) *MockGeneralSettingsClient_UpdateGeneralSettings_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockGeneralSettingsClient_UpdateGeneralSettings_Call) RunAndReturn(run func(*models.UpdateGeneralSettingsV2Request) (*models.PatchGeneralSettingsResponseV2, *apiutils.APIError)) *MockGeneralSettingsClient_UpdateGeneralSettings_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockGeneralSettingsClient creates a new instance of MockGeneralSettingsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockGeneralSettingsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockGeneralSettingsClient {
	mock := &MockGeneralSettingsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
