// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build unit

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockIcebergTableClient creates a new instance of MockIcebergTableClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIcebergTableClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIcebergTableClient {
	mock := &MockIcebergTableClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIcebergTableClient is an autogenerated mock type for the IcebergTableClient type
type MockIcebergTableClient struct {
	mock.Mock
}

type MockIcebergTableClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIcebergTableClient) EXPECT() *MockIcebergTableClient_Expecter {
	return &MockIcebergTableClient_Expecter{mock: &_m.Mock}
}

// ListAwsIcebergTables provides a mock function for the type MockIcebergTableClient
func (_mock *MockIcebergTableClient) ListAwsIcebergTables(limit *int64, start *string, filter *string, embed *string, lookbackDays *int64) (*models.ListIcebergTablesResponse, *apiutils.APIError) {
	ret := _mock.Called(limit, start, filter, embed, lookbackDays)

	if len(ret) == 0 {
		panic("no return value specified for ListAwsIcebergTables")
	}

	var r0 *models.ListIcebergTablesResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *string, *int64) (*models.ListIcebergTablesResponse, *apiutils.APIError)); ok {
		return returnFunc(limit, start, filter, embed, lookbackDays)
	}
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *string, *int64) *models.ListIcebergTablesResponse); ok {
		r0 = returnFunc(limit, start, filter, embed, lookbackDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListIcebergTablesResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*int64, *string, *string, *string, *int64) *apiutils.APIError); ok {
		r1 = returnFunc(limit, start, filter, embed, lookbackDays)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockIcebergTableClient_ListAwsIcebergTables_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAwsIcebergTables'
type MockIcebergTableClient_ListAwsIcebergTables_Call struct {
	*mock.Call
}

// ListAwsIcebergTables is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - filter *string
//   - embed *string
//   - lookbackDays *int64
func (_e *MockIcebergTableClient_Expecter) ListAwsIcebergTables(limit interface{}, start interface{}, filter interface{}, embed interface{}, lookbackDays interface{}) *MockIcebergTableClient_ListAwsIcebergTables_Call {
	return &MockIcebergTableClient_ListAwsIcebergTables_Call{Call: _e.mock.On("ListAwsIcebergTables", limit, start, filter, embed, lookbackDays)}
}

func (_c *MockIcebergTableClient_ListAwsIcebergTables_Call) Run(run func(limit *int64, start *string, filter *string, embed *string, lookbackDays *int64)) *MockIcebergTableClient_ListAwsIcebergTables_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *int64
		if args[0] != nil {
			arg0 = args[0].(*int64)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		var arg4 *int64
		if args[4] != nil {
			arg4 = args[4].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockIcebergTableClient_ListAwsIcebergTables_Call) Return(listIcebergTablesResponse *models.ListIcebergTablesResponse, aPIError *apiutils.APIError) *MockIcebergTableClient_ListAwsIcebergTables_Call {
	_c.Call.Return(listIcebergTablesResponse, aPIError)
	return _c
}

func (_c *MockIcebergTableClient_ListAwsIcebergTables_Call) RunAndReturn(run func(limit *int64, start *string, filter *string, embed *string, lookbackDays *int64) (*models.ListIcebergTablesResponse, *apiutils.APIError)) *MockIcebergTableClient_ListAwsIcebergTables_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAwsIcebergTable provides a mock function for the type MockIcebergTableClient
func (_mock *MockIcebergTableClient) ReadAwsIcebergTable(tableId string, lookbackDays *int64, embed *string) (*models.ReadIcebergTableResponse, *apiutils.APIError) {
	ret := _mock.Called(tableId, lookbackDays, embed)

	if len(ret) == 0 {
		panic("no return value specified for ReadAwsIcebergTable")
	}

	var r0 *models.ReadIcebergTableResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, *int64, *string) (*models.ReadIcebergTableResponse, *apiutils.APIError)); ok {
		return returnFunc(tableId, lookbackDays, embed)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *int64, *string) *models.ReadIcebergTableResponse); ok {
		r0 = returnFunc(tableId, lookbackDays, embed)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadIcebergTableResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *int64, *string) *apiutils.APIError); ok {
		r1 = returnFunc(tableId, lookbackDays, embed)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockIcebergTableClient_ReadAwsIcebergTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAwsIcebergTable'
type MockIcebergTableClient_ReadAwsIcebergTable_Call struct {
	*mock.Call
}

// ReadAwsIcebergTable is a helper method to define mock.On call
//   - tableId string
//   - lookbackDays *int64
//   - embed *string
func (_e *MockIcebergTableClient_Expecter) ReadAwsIcebergTable(tableId interface{}, lookbackDays interface{}, embed interface{}) *MockIcebergTableClient_ReadAwsIcebergTable_Call {
	return &MockIcebergTableClient_ReadAwsIcebergTable_Call{Call: _e.mock.On("ReadAwsIcebergTable", tableId, lookbackDays, embed)}
}

func (_c *MockIcebergTableClient_ReadAwsIcebergTable_Call) Run(run func(tableId string, lookbackDays *int64, embed *string)) *MockIcebergTableClient_ReadAwsIcebergTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockIcebergTableClient_ReadAwsIcebergTable_Call) Return(readIcebergTableResponse *models.ReadIcebergTableResponse, aPIError *apiutils.APIError) *MockIcebergTableClient_ReadAwsIcebergTable_Call {
	_c.Call.Return(readIcebergTableResponse, aPIError)
	return _c
}

func (_c *MockIcebergTableClient_ReadAwsIcebergTable_Call) RunAndReturn(run func(tableId string, lookbackDays *int64, embed *string) (*models.ReadIcebergTableResponse, *apiutils.APIError)) *MockIcebergTableClient_ReadAwsIcebergTable_Call {
	_c.Call.Return(run)
	return _c
}
