// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPostProcessAWSConnectionClient creates a new instance of MockPostProcessAWSConnectionClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPostProcessAWSConnectionClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPostProcessAWSConnectionClient {
	mock := &MockPostProcessAWSConnectionClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPostProcessAWSConnectionClient is an autogenerated mock type for the PostProcessAWSConnectionClient type
type MockPostProcessAWSConnectionClient struct {
	mock.Mock
}

type MockPostProcessAWSConnectionClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPostProcessAWSConnectionClient) EXPECT() *MockPostProcessAWSConnectionClient_Expecter {
	return &MockPostProcessAWSConnectionClient_Expecter{mock: &_m.Mock}
}

// PostProcessAwsConnection provides a mock function for the type MockPostProcessAWSConnectionClient
func (_mock *MockPostProcessAWSConnectionClient) PostProcessAwsConnection(body *models.PostProcessAwsConnectionV1Request) (interface{}, *apiutils.APIError) {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for PostProcessAwsConnection")
	}

	var r0 interface{}
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*models.PostProcessAwsConnectionV1Request) (interface{}, *apiutils.APIError)); ok {
		return returnFunc(body)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.PostProcessAwsConnectionV1Request) interface{}); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.PostProcessAwsConnectionV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockPostProcessAWSConnectionClient_PostProcessAwsConnection_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostProcessAwsConnection'
type MockPostProcessAWSConnectionClient_PostProcessAwsConnection_Call struct {
	*mock.Call
}

// PostProcessAwsConnection is a helper method to define mock.On call
//   - body *models.PostProcessAwsConnectionV1Request
func (_e *MockPostProcessAWSConnectionClient_Expecter) PostProcessAwsConnection(body interface{}) *MockPostProcessAWSConnectionClient_PostProcessAwsConnection_Call {
	return &MockPostProcessAWSConnectionClient_PostProcessAwsConnection_Call{Call: _e.mock.On("PostProcessAwsConnection", body)}
}

func (_c *MockPostProcessAWSConnectionClient_PostProcessAwsConnection_Call) Run(run func(body *models.PostProcessAwsConnectionV1Request)) *MockPostProcessAWSConnectionClient_PostProcessAwsConnection_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.PostProcessAwsConnectionV1Request
		if args[0] != nil {
			arg0 = args[0].(*models.PostProcessAwsConnectionV1Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPostProcessAWSConnectionClient_PostProcessAwsConnection_Call) Return(ifaceVal interface{}, aPIError *apiutils.APIError) *MockPostProcessAWSConnectionClient_PostProcessAwsConnection_Call {
	_c.Call.Return(ifaceVal, aPIError)
	return _c
}

func (_c *MockPostProcessAWSConnectionClient_PostProcessAwsConnection_Call) RunAndReturn(run func(body *models.PostProcessAwsConnectionV1Request) (interface{}, *apiutils.APIError)) *MockPostProcessAWSConnectionClient_PostProcessAwsConnection_Call {
	_c.Call.Return(run)
	return _c
}
