// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockProtectionGroupS3AssetsClient creates a new instance of MockProtectionGroupS3AssetsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProtectionGroupS3AssetsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProtectionGroupS3AssetsClient {
	mock := &MockProtectionGroupS3AssetsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProtectionGroupS3AssetsClient is an autogenerated mock type for the ProtectionGroupS3AssetsClient type
type MockProtectionGroupS3AssetsClient struct {
	mock.Mock
}

type MockProtectionGroupS3AssetsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProtectionGroupS3AssetsClient) EXPECT() *MockProtectionGroupS3AssetsClient_Expecter {
	return &MockProtectionGroupS3AssetsClient_Expecter{mock: &_m.Mock}
}

// ListProtectionGroupS3AssetPitrIntervals provides a mock function for the type MockProtectionGroupS3AssetsClient
func (_mock *MockProtectionGroupS3AssetsClient) ListProtectionGroupS3AssetPitrIntervals(protectionGroupS3AssetId string, limit *int64, start *string, filter *string) (*models.ListProtectionGroupS3AssetPitrIntervalsResponse, *apiutils.APIError) {
	ret := _mock.Called(protectionGroupS3AssetId, limit, start, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListProtectionGroupS3AssetPitrIntervals")
	}

	var r0 *models.ListProtectionGroupS3AssetPitrIntervalsResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, *int64, *string, *string) (*models.ListProtectionGroupS3AssetPitrIntervalsResponse, *apiutils.APIError)); ok {
		return returnFunc(protectionGroupS3AssetId, limit, start, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *int64, *string, *string) *models.ListProtectionGroupS3AssetPitrIntervalsResponse); ok {
		r0 = returnFunc(protectionGroupS3AssetId, limit, start, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListProtectionGroupS3AssetPitrIntervalsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *int64, *string, *string) *apiutils.APIError); ok {
		r1 = returnFunc(protectionGroupS3AssetId, limit, start, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockProtectionGroupS3AssetsClient_ListProtectionGroupS3AssetPitrIntervals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProtectionGroupS3AssetPitrIntervals'
type MockProtectionGroupS3AssetsClient_ListProtectionGroupS3AssetPitrIntervals_Call struct {
	*mock.Call
}

// ListProtectionGroupS3AssetPitrIntervals is a helper method to define mock.On call
//   - protectionGroupS3AssetId string
//   - limit *int64
//   - start *string
//   - filter *string
func (_e *MockProtectionGroupS3AssetsClient_Expecter) ListProtectionGroupS3AssetPitrIntervals(protectionGroupS3AssetId interface{}, limit interface{}, start interface{}, filter interface{}) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3AssetPitrIntervals_Call {
	return &MockProtectionGroupS3AssetsClient_ListProtectionGroupS3AssetPitrIntervals_Call{Call: _e.mock.On("ListProtectionGroupS3AssetPitrIntervals", protectionGroupS3AssetId, limit, start, filter)}
}

func (_c *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3AssetPitrIntervals_Call) Run(run func(protectionGroupS3AssetId string, limit *int64, start *string, filter *string)) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3AssetPitrIntervals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *string
		if args[3] != nil {
			arg3 = args[3].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3AssetPitrIntervals_Call) Return(listProtectionGroupS3AssetPitrIntervalsResponse *models.ListProtectionGroupS3AssetPitrIntervalsResponse, aPIError *apiutils.APIError) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3AssetPitrIntervals_Call {
	_c.Call.Return(listProtectionGroupS3AssetPitrIntervalsResponse, aPIError)
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3AssetPitrIntervals_Call) RunAndReturn(run func(protectionGroupS3AssetId string, limit *int64, start *string, filter *string) (*models.ListProtectionGroupS3AssetPitrIntervalsResponse, *apiutils.APIError)) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3AssetPitrIntervals_Call {
	_c.Call.Return(run)
	return _c
}

// ListProtectionGroupS3Assets provides a mock function for the type MockProtectionGroupS3AssetsClient
func (_mock *MockProtectionGroupS3AssetsClient) ListProtectionGroupS3Assets(limit *int64, start *string, filter *string, lookbackDays *int64) (*models.ListProtectionGroupS3AssetsResponse, *apiutils.APIError) {
	ret := _mock.Called(limit, start, filter, lookbackDays)

	if len(ret) == 0 {
		panic("no return value specified for ListProtectionGroupS3Assets")
	}

	var r0 *models.ListProtectionGroupS3AssetsResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *int64) (*models.ListProtectionGroupS3AssetsResponse, *apiutils.APIError)); ok {
		return returnFunc(limit, start, filter, lookbackDays)
	}
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string, *int64) *models.ListProtectionGroupS3AssetsResponse); ok {
		r0 = returnFunc(limit, start, filter, lookbackDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListProtectionGroupS3AssetsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*int64, *string, *string, *int64) *apiutils.APIError); ok {
		r1 = returnFunc(limit, start, filter, lookbackDays)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProtectionGroupS3Assets'
type MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call struct {
	*mock.Call
}

// ListProtectionGroupS3Assets is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - filter *string
//   - lookbackDays *int64
func (_e *MockProtectionGroupS3AssetsClient_Expecter) ListProtectionGroupS3Assets(limit interface{}, start interface{}, filter interface{}, lookbackDays interface{}) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call {
	return &MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call{Call: _e.mock.On("ListProtectionGroupS3Assets", limit, start, filter, lookbackDays)}
}

func (_c *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call) Run(run func(limit *int64, start *string, filter *string, lookbackDays *int64)) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *int64
		if args[0] != nil {
			arg0 = args[0].(*int64)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 *int64
		if args[3] != nil {
			arg3 = args[3].(*int64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call) Return(listProtectionGroupS3AssetsResponse *models.ListProtectionGroupS3AssetsResponse, aPIError *apiutils.APIError) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call {
	_c.Call.Return(listProtectionGroupS3AssetsResponse, aPIError)
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call) RunAndReturn(run func(limit *int64, start *string, filter *string, lookbackDays *int64) (*models.ListProtectionGroupS3AssetsResponse, *apiutils.APIError)) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call {
	_c.Call.Return(run)
	return _c
}

// ReadProtectionGroupS3Asset provides a mock function for the type MockProtectionGroupS3AssetsClient
func (_mock *MockProtectionGroupS3AssetsClient) ReadProtectionGroupS3Asset(protectionGroupS3AssetId string, lookbackDays *int64) (*models.ReadProtectionGroupS3AssetResponse, *apiutils.APIError) {
	ret := _mock.Called(protectionGroupS3AssetId, lookbackDays)

	if len(ret) == 0 {
		panic("no return value specified for ReadProtectionGroupS3Asset")
	}

	var r0 *models.ReadProtectionGroupS3AssetResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, *int64) (*models.ReadProtectionGroupS3AssetResponse, *apiutils.APIError)); ok {
		return returnFunc(protectionGroupS3AssetId, lookbackDays)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *int64) *models.ReadProtectionGroupS3AssetResponse); ok {
		r0 = returnFunc(protectionGroupS3AssetId, lookbackDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadProtectionGroupS3AssetResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *int64) *apiutils.APIError); ok {
		r1 = returnFunc(protectionGroupS3AssetId, lookbackDays)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadProtectionGroupS3Asset'
type MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call struct {
	*mock.Call
}

// ReadProtectionGroupS3Asset is a helper method to define mock.On call
//   - protectionGroupS3AssetId string
//   - lookbackDays *int64
func (_e *MockProtectionGroupS3AssetsClient_Expecter) ReadProtectionGroupS3Asset(protectionGroupS3AssetId interface{}, lookbackDays interface{}) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call {
	return &MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call{Call: _e.mock.On("ReadProtectionGroupS3Asset", protectionGroupS3AssetId, lookbackDays)}
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call) Run(run func(protectionGroupS3AssetId string, lookbackDays *int64)) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *int64
		if args[1] != nil {
			arg1 = args[1].(*int64)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call) Return(readProtectionGroupS3AssetResponse *models.ReadProtectionGroupS3AssetResponse, aPIError *apiutils.APIError) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call {
	_c.Call.Return(readProtectionGroupS3AssetResponse, aPIError)
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call) RunAndReturn(run func(protectionGroupS3AssetId string, lookbackDays *int64) (*models.ReadProtectionGroupS3AssetResponse, *apiutils.APIError)) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call {
	_c.Call.Return(run)
	return _c
}

// ReadProtectionGroupS3AssetContinuousBackupStats provides a mock function for the type MockProtectionGroupS3AssetsClient
func (_mock *MockProtectionGroupS3AssetsClient) ReadProtectionGroupS3AssetContinuousBackupStats(protectionGroupS3AssetId string, bucketName *string, bucketId *string, beginTimestamp string, endTimestamp string, interval *string) (*models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse, *apiutils.APIError) {
	ret := _mock.Called(protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval)

	if len(ret) == 0 {
		panic("no return value specified for ReadProtectionGroupS3AssetContinuousBackupStats")
	}

	var r0 *models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, *string, *string, string, string, *string) (*models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse, *apiutils.APIError)); ok {
		return returnFunc(protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *string, *string, string, string, *string) *models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse); ok {
		r0 = returnFunc(protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *string, *string, string, string, *string) *apiutils.APIError); ok {
		r1 = returnFunc(protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadProtectionGroupS3AssetContinuousBackupStats'
type MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call struct {
	*mock.Call
}

// ReadProtectionGroupS3AssetContinuousBackupStats is a helper method to define mock.On call
//   - protectionGroupS3AssetId string
//   - bucketName *string
//   - bucketId *string
//   - beginTimestamp string
//   - endTimestamp string
//   - interval *string
func (_e *MockProtectionGroupS3AssetsClient_Expecter) ReadProtectionGroupS3AssetContinuousBackupStats(protectionGroupS3AssetId interface{}, bucketName interface{}, bucketId interface{}, beginTimestamp interface{}, endTimestamp interface{}, interval interface{}) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call {
	return &MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call{Call: _e.mock.On("ReadProtectionGroupS3AssetContinuousBackupStats", protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval)}
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call) Run(run func(protectionGroupS3AssetId string, bucketName *string, bucketId *string, beginTimestamp string, endTimestamp string, interval *string)) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 *string
		if args[5] != nil {
			arg5 = args[5].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call) Return(readProtectionGroupS3AssetContinuousBackupStatsResponse *models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse, aPIError *apiutils.APIError) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call {
	_c.Call.Return(readProtectionGroupS3AssetContinuousBackupStatsResponse, aPIError)
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call) RunAndReturn(run func(protectionGroupS3AssetId string, bucketName *string, bucketId *string, beginTimestamp string, endTimestamp string, interval *string) (*models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse, *apiutils.APIError)) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call {
	_c.Call.Return(run)
	return _c
}
