// Code generated by mockery. DO NOT EDIT.

package sdkclients

import (
	apiutils "github.com/clumio-code/clumio-go-sdk/api_utils"
	mock "github.com/stretchr/testify/mock"

	models "github.com/clumio-code/clumio-go-sdk/models"
)

// MockProtectionGroupS3AssetsClient is an autogenerated mock type for the ProtectionGroupS3AssetsClient type
type MockProtectionGroupS3AssetsClient struct {
	mock.Mock
}

type MockProtectionGroupS3AssetsClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProtectionGroupS3AssetsClient) EXPECT() *MockProtectionGroupS3AssetsClient_Expecter {
	return &MockProtectionGroupS3AssetsClient_Expecter{mock: &_m.Mock}
}

// ListProtectionGroupS3Assets provides a mock function with given fields: limit, start, filter
func (_m *MockProtectionGroupS3AssetsClient) ListProtectionGroupS3Assets(limit *int64, start *string, filter *string) (*models.ListProtectionGroupS3AssetsResponse, *apiutils.APIError) {
	ret := _m.Called(limit, start, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListProtectionGroupS3Assets")
	}

	var r0 *models.ListProtectionGroupS3AssetsResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(*int64, *string, *string) (*models.ListProtectionGroupS3AssetsResponse, *apiutils.APIError)); ok {
		return rf(limit, start, filter)
	}
	if rf, ok := ret.Get(0).(func(*int64, *string, *string) *models.ListProtectionGroupS3AssetsResponse); ok {
		r0 = rf(limit, start, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListProtectionGroupS3AssetsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*int64, *string, *string) *apiutils.APIError); ok {
		r1 = rf(limit, start, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListProtectionGroupS3Assets'
type MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call struct {
	*mock.Call
}

// ListProtectionGroupS3Assets is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - filter *string
func (_e *MockProtectionGroupS3AssetsClient_Expecter) ListProtectionGroupS3Assets(limit interface{}, start interface{}, filter interface{}) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call {
	return &MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call{Call: _e.mock.On("ListProtectionGroupS3Assets", limit, start, filter)}
}

func (_c *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call) Run(run func(limit *int64, start *string, filter *string)) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*int64), args[1].(*string), args[2].(*string))
	})
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call) Return(_a0 *models.ListProtectionGroupS3AssetsResponse, _a1 *apiutils.APIError) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call) RunAndReturn(run func(*int64, *string, *string) (*models.ListProtectionGroupS3AssetsResponse, *apiutils.APIError)) *MockProtectionGroupS3AssetsClient_ListProtectionGroupS3Assets_Call {
	_c.Call.Return(run)
	return _c
}

// ReadProtectionGroupS3Asset provides a mock function with given fields: protectionGroupS3AssetId
func (_m *MockProtectionGroupS3AssetsClient) ReadProtectionGroupS3Asset(protectionGroupS3AssetId string) (*models.ReadProtectionGroupS3AssetResponse, *apiutils.APIError) {
	ret := _m.Called(protectionGroupS3AssetId)

	if len(ret) == 0 {
		panic("no return value specified for ReadProtectionGroupS3Asset")
	}

	var r0 *models.ReadProtectionGroupS3AssetResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(string) (*models.ReadProtectionGroupS3AssetResponse, *apiutils.APIError)); ok {
		return rf(protectionGroupS3AssetId)
	}
	if rf, ok := ret.Get(0).(func(string) *models.ReadProtectionGroupS3AssetResponse); ok {
		r0 = rf(protectionGroupS3AssetId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadProtectionGroupS3AssetResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = rf(protectionGroupS3AssetId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadProtectionGroupS3Asset'
type MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call struct {
	*mock.Call
}

// ReadProtectionGroupS3Asset is a helper method to define mock.On call
//   - protectionGroupS3AssetId string
func (_e *MockProtectionGroupS3AssetsClient_Expecter) ReadProtectionGroupS3Asset(protectionGroupS3AssetId interface{}) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call {
	return &MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call{Call: _e.mock.On("ReadProtectionGroupS3Asset", protectionGroupS3AssetId)}
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call) Run(run func(protectionGroupS3AssetId string)) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call) Return(_a0 *models.ReadProtectionGroupS3AssetResponse, _a1 *apiutils.APIError) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call) RunAndReturn(run func(string) (*models.ReadProtectionGroupS3AssetResponse, *apiutils.APIError)) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3Asset_Call {
	_c.Call.Return(run)
	return _c
}

// ReadProtectionGroupS3AssetContinuousBackupStats provides a mock function with given fields: protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval
func (_m *MockProtectionGroupS3AssetsClient) ReadProtectionGroupS3AssetContinuousBackupStats(protectionGroupS3AssetId string, bucketName *string, bucketId *string, beginTimestamp string, endTimestamp string, interval *string) (*models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse, *apiutils.APIError) {
	ret := _m.Called(protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval)

	if len(ret) == 0 {
		panic("no return value specified for ReadProtectionGroupS3AssetContinuousBackupStats")
	}

	var r0 *models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(string, *string, *string, string, string, *string) (*models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse, *apiutils.APIError)); ok {
		return rf(protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval)
	}
	if rf, ok := ret.Get(0).(func(string, *string, *string, string, string, *string) *models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse); ok {
		r0 = rf(protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *string, *string, string, string, *string) *apiutils.APIError); ok {
		r1 = rf(protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadProtectionGroupS3AssetContinuousBackupStats'
type MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call struct {
	*mock.Call
}

// ReadProtectionGroupS3AssetContinuousBackupStats is a helper method to define mock.On call
//   - protectionGroupS3AssetId string
//   - bucketName *string
//   - bucketId *string
//   - beginTimestamp string
//   - endTimestamp string
//   - interval *string
func (_e *MockProtectionGroupS3AssetsClient_Expecter) ReadProtectionGroupS3AssetContinuousBackupStats(protectionGroupS3AssetId interface{}, bucketName interface{}, bucketId interface{}, beginTimestamp interface{}, endTimestamp interface{}, interval interface{}) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call {
	return &MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call{Call: _e.mock.On("ReadProtectionGroupS3AssetContinuousBackupStats", protectionGroupS3AssetId, bucketName, bucketId, beginTimestamp, endTimestamp, interval)}
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call) Run(run func(protectionGroupS3AssetId string, bucketName *string, bucketId *string, beginTimestamp string, endTimestamp string, interval *string)) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*string), args[2].(*string), args[3].(string), args[4].(string), args[5].(*string))
	})
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call) Return(_a0 *models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse, _a1 *apiutils.APIError) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call) RunAndReturn(run func(string, *string, *string, string, string, *string) (*models.ReadProtectionGroupS3AssetContinuousBackupStatsResponse, *apiutils.APIError)) *MockProtectionGroupS3AssetsClient_ReadProtectionGroupS3AssetContinuousBackupStats_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockProtectionGroupS3AssetsClient creates a new instance of MockProtectionGroupS3AssetsClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProtectionGroupS3AssetsClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProtectionGroupS3AssetsClient {
	mock := &MockProtectionGroupS3AssetsClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
