// Code generated by mockery. DO NOT EDIT.

package sdkclients

import (
	apiutils "github.com/clumio-code/clumio-go-sdk/api_utils"
	mock "github.com/stretchr/testify/mock"

	models "github.com/clumio-code/clumio-go-sdk/models"
)

// MockReportConfigurationClient is an autogenerated mock type for the ReportConfigurationClient type
type MockReportConfigurationClient struct {
	mock.Mock
}

type MockReportConfigurationClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportConfigurationClient) EXPECT() *MockReportConfigurationClient_Expecter {
	return &MockReportConfigurationClient_Expecter{mock: &_m.Mock}
}

// CreateComplianceReportConfiguration provides a mock function with given fields: body
func (_m *MockReportConfigurationClient) CreateComplianceReportConfiguration(body *models.CreateComplianceReportConfigurationV1Request) (*models.CreateComplianceConfigurationResponse, *apiutils.APIError) {
	ret := _m.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CreateComplianceReportConfiguration")
	}

	var r0 *models.CreateComplianceConfigurationResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(*models.CreateComplianceReportConfigurationV1Request) (*models.CreateComplianceConfigurationResponse, *apiutils.APIError)); ok {
		return rf(body)
	}
	if rf, ok := ret.Get(0).(func(*models.CreateComplianceReportConfigurationV1Request) *models.CreateComplianceConfigurationResponse); ok {
		r0 = rf(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CreateComplianceConfigurationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*models.CreateComplianceReportConfigurationV1Request) *apiutils.APIError); ok {
		r1 = rf(body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockReportConfigurationClient_CreateComplianceReportConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComplianceReportConfiguration'
type MockReportConfigurationClient_CreateComplianceReportConfiguration_Call struct {
	*mock.Call
}

// CreateComplianceReportConfiguration is a helper method to define mock.On call
//   - body *models.CreateComplianceReportConfigurationV1Request
func (_e *MockReportConfigurationClient_Expecter) CreateComplianceReportConfiguration(body interface{}) *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call {
	return &MockReportConfigurationClient_CreateComplianceReportConfiguration_Call{Call: _e.mock.On("CreateComplianceReportConfiguration", body)}
}

func (_c *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call) Run(run func(body *models.CreateComplianceReportConfigurationV1Request)) *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.CreateComplianceReportConfigurationV1Request))
	})
	return _c
}

func (_c *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call) Return(_a0 *models.CreateComplianceConfigurationResponse, _a1 *apiutils.APIError) *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call) RunAndReturn(run func(*models.CreateComplianceReportConfigurationV1Request) (*models.CreateComplianceConfigurationResponse, *apiutils.APIError)) *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComplianceReportConfiguration provides a mock function with given fields: configurationId
func (_m *MockReportConfigurationClient) DeleteComplianceReportConfiguration(configurationId string) (interface{}, *apiutils.APIError) {
	ret := _m.Called(configurationId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComplianceReportConfiguration")
	}

	var r0 interface{}
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(string) (interface{}, *apiutils.APIError)); ok {
		return rf(configurationId)
	}
	if rf, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = rf(configurationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}

	if rf, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = rf(configurationId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComplianceReportConfiguration'
type MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call struct {
	*mock.Call
}

// DeleteComplianceReportConfiguration is a helper method to define mock.On call
//   - configurationId string
func (_e *MockReportConfigurationClient_Expecter) DeleteComplianceReportConfiguration(configurationId interface{}) *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call {
	return &MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call{Call: _e.mock.On("DeleteComplianceReportConfiguration", configurationId)}
}

func (_c *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call) Run(run func(configurationId string)) *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call) Return(_a0 interface{}, _a1 *apiutils.APIError) *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call) RunAndReturn(run func(string) (interface{}, *apiutils.APIError)) *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// ListComplianceReportConfigurations provides a mock function with given fields: limit, start, filter
func (_m *MockReportConfigurationClient) ListComplianceReportConfigurations(limit *int64, start *string, filter *string) (*models.ListComplianceConfigurationsResponse, *apiutils.APIError) {
	ret := _m.Called(limit, start, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListComplianceReportConfigurations")
	}

	var r0 *models.ListComplianceConfigurationsResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(*int64, *string, *string) (*models.ListComplianceConfigurationsResponse, *apiutils.APIError)); ok {
		return rf(limit, start, filter)
	}
	if rf, ok := ret.Get(0).(func(*int64, *string, *string) *models.ListComplianceConfigurationsResponse); ok {
		r0 = rf(limit, start, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListComplianceConfigurationsResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(*int64, *string, *string) *apiutils.APIError); ok {
		r1 = rf(limit, start, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockReportConfigurationClient_ListComplianceReportConfigurations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComplianceReportConfigurations'
type MockReportConfigurationClient_ListComplianceReportConfigurations_Call struct {
	*mock.Call
}

// ListComplianceReportConfigurations is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - filter *string
func (_e *MockReportConfigurationClient_Expecter) ListComplianceReportConfigurations(limit interface{}, start interface{}, filter interface{}) *MockReportConfigurationClient_ListComplianceReportConfigurations_Call {
	return &MockReportConfigurationClient_ListComplianceReportConfigurations_Call{Call: _e.mock.On("ListComplianceReportConfigurations", limit, start, filter)}
}

func (_c *MockReportConfigurationClient_ListComplianceReportConfigurations_Call) Run(run func(limit *int64, start *string, filter *string)) *MockReportConfigurationClient_ListComplianceReportConfigurations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*int64), args[1].(*string), args[2].(*string))
	})
	return _c
}

func (_c *MockReportConfigurationClient_ListComplianceReportConfigurations_Call) Return(_a0 *models.ListComplianceConfigurationsResponse, _a1 *apiutils.APIError) *MockReportConfigurationClient_ListComplianceReportConfigurations_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportConfigurationClient_ListComplianceReportConfigurations_Call) RunAndReturn(run func(*int64, *string, *string) (*models.ListComplianceConfigurationsResponse, *apiutils.APIError)) *MockReportConfigurationClient_ListComplianceReportConfigurations_Call {
	_c.Call.Return(run)
	return _c
}

// ReadComplianceReportConfiguration provides a mock function with given fields: configurationId
func (_m *MockReportConfigurationClient) ReadComplianceReportConfiguration(configurationId string) (*models.ReadComplianceConfigurationResponse, *apiutils.APIError) {
	ret := _m.Called(configurationId)

	if len(ret) == 0 {
		panic("no return value specified for ReadComplianceReportConfiguration")
	}

	var r0 *models.ReadComplianceConfigurationResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(string) (*models.ReadComplianceConfigurationResponse, *apiutils.APIError)); ok {
		return rf(configurationId)
	}
	if rf, ok := ret.Get(0).(func(string) *models.ReadComplianceConfigurationResponse); ok {
		r0 = rf(configurationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadComplianceConfigurationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = rf(configurationId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockReportConfigurationClient_ReadComplianceReportConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadComplianceReportConfiguration'
type MockReportConfigurationClient_ReadComplianceReportConfiguration_Call struct {
	*mock.Call
}

// ReadComplianceReportConfiguration is a helper method to define mock.On call
//   - configurationId string
func (_e *MockReportConfigurationClient_Expecter) ReadComplianceReportConfiguration(configurationId interface{}) *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call {
	return &MockReportConfigurationClient_ReadComplianceReportConfiguration_Call{Call: _e.mock.On("ReadComplianceReportConfiguration", configurationId)}
}

func (_c *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call) Run(run func(configurationId string)) *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call) Return(_a0 *models.ReadComplianceConfigurationResponse, _a1 *apiutils.APIError) *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call) RunAndReturn(run func(string) (*models.ReadComplianceConfigurationResponse, *apiutils.APIError)) *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComplianceReportConfiguration provides a mock function with given fields: configurationId, body
func (_m *MockReportConfigurationClient) UpdateComplianceReportConfiguration(configurationId string, body *models.UpdateComplianceReportConfigurationV1Request) (*models.UpdateComplianceConfigurationResponse, *apiutils.APIError) {
	ret := _m.Called(configurationId, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComplianceReportConfiguration")
	}

	var r0 *models.UpdateComplianceConfigurationResponse
	var r1 *apiutils.APIError
	if rf, ok := ret.Get(0).(func(string, *models.UpdateComplianceReportConfigurationV1Request) (*models.UpdateComplianceConfigurationResponse, *apiutils.APIError)); ok {
		return rf(configurationId, body)
	}
	if rf, ok := ret.Get(0).(func(string, *models.UpdateComplianceReportConfigurationV1Request) *models.UpdateComplianceConfigurationResponse); ok {
		r0 = rf(configurationId, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UpdateComplianceConfigurationResponse)
		}
	}

	if rf, ok := ret.Get(1).(func(string, *models.UpdateComplianceReportConfigurationV1Request) *apiutils.APIError); ok {
		r1 = rf(configurationId, body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}

	return r0, r1
}

// MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComplianceReportConfiguration'
type MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call struct {
	*mock.Call
}

// UpdateComplianceReportConfiguration is a helper method to define mock.On call
//   - configurationId string
//   - body *models.UpdateComplianceReportConfigurationV1Request
func (_e *MockReportConfigurationClient_Expecter) UpdateComplianceReportConfiguration(configurationId interface{}, body interface{}) *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call {
	return &MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call{Call: _e.mock.On("UpdateComplianceReportConfiguration", configurationId, body)}
}

func (_c *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call) Run(run func(configurationId string, body *models.UpdateComplianceReportConfigurationV1Request)) *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(*models.UpdateComplianceReportConfigurationV1Request))
	})
	return _c
}

func (_c *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call) Return(_a0 *models.UpdateComplianceConfigurationResponse, _a1 *apiutils.APIError) *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call) RunAndReturn(run func(string, *models.UpdateComplianceReportConfigurationV1Request) (*models.UpdateComplianceConfigurationResponse, *apiutils.APIError)) *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockReportConfigurationClient creates a new instance of MockReportConfigurationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportConfigurationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportConfigurationClient {
	mock := &MockReportConfigurationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
