// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockReportConfigurationClient creates a new instance of MockReportConfigurationClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockReportConfigurationClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockReportConfigurationClient {
	mock := &MockReportConfigurationClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockReportConfigurationClient is an autogenerated mock type for the ReportConfigurationClient type
type MockReportConfigurationClient struct {
	mock.Mock
}

type MockReportConfigurationClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockReportConfigurationClient) EXPECT() *MockReportConfigurationClient_Expecter {
	return &MockReportConfigurationClient_Expecter{mock: &_m.Mock}
}

// CreateComplianceReportConfiguration provides a mock function for the type MockReportConfigurationClient
func (_mock *MockReportConfigurationClient) CreateComplianceReportConfiguration(body *models.CreateComplianceReportConfigurationV1Request) (*models.CreateComplianceConfigurationResponse, *apiutils.APIError) {
	ret := _mock.Called(body)

	if len(ret) == 0 {
		panic("no return value specified for CreateComplianceReportConfiguration")
	}

	var r0 *models.CreateComplianceConfigurationResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*models.CreateComplianceReportConfigurationV1Request) (*models.CreateComplianceConfigurationResponse, *apiutils.APIError)); ok {
		return returnFunc(body)
	}
	if returnFunc, ok := ret.Get(0).(func(*models.CreateComplianceReportConfigurationV1Request) *models.CreateComplianceConfigurationResponse); ok {
		r0 = returnFunc(body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.CreateComplianceConfigurationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*models.CreateComplianceReportConfigurationV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockReportConfigurationClient_CreateComplianceReportConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComplianceReportConfiguration'
type MockReportConfigurationClient_CreateComplianceReportConfiguration_Call struct {
	*mock.Call
}

// CreateComplianceReportConfiguration is a helper method to define mock.On call
//   - body *models.CreateComplianceReportConfigurationV1Request
func (_e *MockReportConfigurationClient_Expecter) CreateComplianceReportConfiguration(body interface{}) *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call {
	return &MockReportConfigurationClient_CreateComplianceReportConfiguration_Call{Call: _e.mock.On("CreateComplianceReportConfiguration", body)}
}

func (_c *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call) Run(run func(body *models.CreateComplianceReportConfigurationV1Request)) *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *models.CreateComplianceReportConfigurationV1Request
		if args[0] != nil {
			arg0 = args[0].(*models.CreateComplianceReportConfigurationV1Request)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call) Return(createComplianceConfigurationResponse *models.CreateComplianceConfigurationResponse, aPIError *apiutils.APIError) *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call {
	_c.Call.Return(createComplianceConfigurationResponse, aPIError)
	return _c
}

func (_c *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call) RunAndReturn(run func(body *models.CreateComplianceReportConfigurationV1Request) (*models.CreateComplianceConfigurationResponse, *apiutils.APIError)) *MockReportConfigurationClient_CreateComplianceReportConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComplianceReportConfiguration provides a mock function for the type MockReportConfigurationClient
func (_mock *MockReportConfigurationClient) DeleteComplianceReportConfiguration(configurationId string) (interface{}, *apiutils.APIError) {
	ret := _mock.Called(configurationId)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComplianceReportConfiguration")
	}

	var r0 interface{}
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string) (interface{}, *apiutils.APIError)); ok {
		return returnFunc(configurationId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) interface{}); ok {
		r0 = returnFunc(configurationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interface{})
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = returnFunc(configurationId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComplianceReportConfiguration'
type MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call struct {
	*mock.Call
}

// DeleteComplianceReportConfiguration is a helper method to define mock.On call
//   - configurationId string
func (_e *MockReportConfigurationClient_Expecter) DeleteComplianceReportConfiguration(configurationId interface{}) *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call {
	return &MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call{Call: _e.mock.On("DeleteComplianceReportConfiguration", configurationId)}
}

func (_c *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call) Run(run func(configurationId string)) *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call) Return(ifaceVal interface{}, aPIError *apiutils.APIError) *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call {
	_c.Call.Return(ifaceVal, aPIError)
	return _c
}

func (_c *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call) RunAndReturn(run func(configurationId string) (interface{}, *apiutils.APIError)) *MockReportConfigurationClient_DeleteComplianceReportConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// ListComplianceReportConfigurations provides a mock function for the type MockReportConfigurationClient
func (_mock *MockReportConfigurationClient) ListComplianceReportConfigurations(limit *int64, start *string, filter *string) (*models.ListComplianceConfigurationsResponse, *apiutils.APIError) {
	ret := _mock.Called(limit, start, filter)

	if len(ret) == 0 {
		panic("no return value specified for ListComplianceReportConfigurations")
	}

	var r0 *models.ListComplianceConfigurationsResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string) (*models.ListComplianceConfigurationsResponse, *apiutils.APIError)); ok {
		return returnFunc(limit, start, filter)
	}
	if returnFunc, ok := ret.Get(0).(func(*int64, *string, *string) *models.ListComplianceConfigurationsResponse); ok {
		r0 = returnFunc(limit, start, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ListComplianceConfigurationsResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*int64, *string, *string) *apiutils.APIError); ok {
		r1 = returnFunc(limit, start, filter)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockReportConfigurationClient_ListComplianceReportConfigurations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListComplianceReportConfigurations'
type MockReportConfigurationClient_ListComplianceReportConfigurations_Call struct {
	*mock.Call
}

// ListComplianceReportConfigurations is a helper method to define mock.On call
//   - limit *int64
//   - start *string
//   - filter *string
func (_e *MockReportConfigurationClient_Expecter) ListComplianceReportConfigurations(limit interface{}, start interface{}, filter interface{}) *MockReportConfigurationClient_ListComplianceReportConfigurations_Call {
	return &MockReportConfigurationClient_ListComplianceReportConfigurations_Call{Call: _e.mock.On("ListComplianceReportConfigurations", limit, start, filter)}
}

func (_c *MockReportConfigurationClient_ListComplianceReportConfigurations_Call) Run(run func(limit *int64, start *string, filter *string)) *MockReportConfigurationClient_ListComplianceReportConfigurations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *int64
		if args[0] != nil {
			arg0 = args[0].(*int64)
		}
		var arg1 *string
		if args[1] != nil {
			arg1 = args[1].(*string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockReportConfigurationClient_ListComplianceReportConfigurations_Call) Return(listComplianceConfigurationsResponse *models.ListComplianceConfigurationsResponse, aPIError *apiutils.APIError) *MockReportConfigurationClient_ListComplianceReportConfigurations_Call {
	_c.Call.Return(listComplianceConfigurationsResponse, aPIError)
	return _c
}

func (_c *MockReportConfigurationClient_ListComplianceReportConfigurations_Call) RunAndReturn(run func(limit *int64, start *string, filter *string) (*models.ListComplianceConfigurationsResponse, *apiutils.APIError)) *MockReportConfigurationClient_ListComplianceReportConfigurations_Call {
	_c.Call.Return(run)
	return _c
}

// ReadComplianceReportConfiguration provides a mock function for the type MockReportConfigurationClient
func (_mock *MockReportConfigurationClient) ReadComplianceReportConfiguration(configurationId string) (*models.ReadComplianceConfigurationResponse, *apiutils.APIError) {
	ret := _mock.Called(configurationId)

	if len(ret) == 0 {
		panic("no return value specified for ReadComplianceReportConfiguration")
	}

	var r0 *models.ReadComplianceConfigurationResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string) (*models.ReadComplianceConfigurationResponse, *apiutils.APIError)); ok {
		return returnFunc(configurationId)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *models.ReadComplianceConfigurationResponse); ok {
		r0 = returnFunc(configurationId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ReadComplianceConfigurationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) *apiutils.APIError); ok {
		r1 = returnFunc(configurationId)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockReportConfigurationClient_ReadComplianceReportConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadComplianceReportConfiguration'
type MockReportConfigurationClient_ReadComplianceReportConfiguration_Call struct {
	*mock.Call
}

// ReadComplianceReportConfiguration is a helper method to define mock.On call
//   - configurationId string
func (_e *MockReportConfigurationClient_Expecter) ReadComplianceReportConfiguration(configurationId interface{}) *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call {
	return &MockReportConfigurationClient_ReadComplianceReportConfiguration_Call{Call: _e.mock.On("ReadComplianceReportConfiguration", configurationId)}
}

func (_c *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call) Run(run func(configurationId string)) *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call) Return(readComplianceConfigurationResponse *models.ReadComplianceConfigurationResponse, aPIError *apiutils.APIError) *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call {
	_c.Call.Return(readComplianceConfigurationResponse, aPIError)
	return _c
}

func (_c *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call) RunAndReturn(run func(configurationId string) (*models.ReadComplianceConfigurationResponse, *apiutils.APIError)) *MockReportConfigurationClient_ReadComplianceReportConfiguration_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComplianceReportConfiguration provides a mock function for the type MockReportConfigurationClient
func (_mock *MockReportConfigurationClient) UpdateComplianceReportConfiguration(configurationId string, body *models.UpdateComplianceReportConfigurationV1Request) (*models.UpdateComplianceConfigurationResponse, *apiutils.APIError) {
	ret := _mock.Called(configurationId, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComplianceReportConfiguration")
	}

	var r0 *models.UpdateComplianceConfigurationResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(string, *models.UpdateComplianceReportConfigurationV1Request) (*models.UpdateComplianceConfigurationResponse, *apiutils.APIError)); ok {
		return returnFunc(configurationId, body)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *models.UpdateComplianceReportConfigurationV1Request) *models.UpdateComplianceConfigurationResponse); ok {
		r0 = returnFunc(configurationId, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.UpdateComplianceConfigurationResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *models.UpdateComplianceReportConfigurationV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(configurationId, body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComplianceReportConfiguration'
type MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call struct {
	*mock.Call
}

// UpdateComplianceReportConfiguration is a helper method to define mock.On call
//   - configurationId string
//   - body *models.UpdateComplianceReportConfigurationV1Request
func (_e *MockReportConfigurationClient_Expecter) UpdateComplianceReportConfiguration(configurationId interface{}, body interface{}) *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call {
	return &MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call{Call: _e.mock.On("UpdateComplianceReportConfiguration", configurationId, body)}
}

func (_c *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call) Run(run func(configurationId string, body *models.UpdateComplianceReportConfigurationV1Request)) *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *models.UpdateComplianceReportConfigurationV1Request
		if args[1] != nil {
			arg1 = args[1].(*models.UpdateComplianceReportConfigurationV1Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call) Return(updateComplianceConfigurationResponse *models.UpdateComplianceConfigurationResponse, aPIError *apiutils.APIError) *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call {
	_c.Call.Return(updateComplianceConfigurationResponse, aPIError)
	return _c
}

func (_c *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call) RunAndReturn(run func(configurationId string, body *models.UpdateComplianceReportConfigurationV1Request) (*models.UpdateComplianceConfigurationResponse, *apiutils.APIError)) *MockReportConfigurationClient_UpdateComplianceReportConfiguration_Call {
	_c.Call.Return(run)
	return _c
}
