// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

//go:build unit

package sdkclients

import (
	"github.com/clumio-code/clumio-go-sdk/api_utils"
	"github.com/clumio-code/clumio-go-sdk/models"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRestoredDynamoDBTableClient creates a new instance of MockRestoredDynamoDBTableClient. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRestoredDynamoDBTableClient(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRestoredDynamoDBTableClient {
	mock := &MockRestoredDynamoDBTableClient{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRestoredDynamoDBTableClient is an autogenerated mock type for the RestoredDynamoDBTableClient type
type MockRestoredDynamoDBTableClient struct {
	mock.Mock
}

type MockRestoredDynamoDBTableClient_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRestoredDynamoDBTableClient) EXPECT() *MockRestoredDynamoDBTableClient_Expecter {
	return &MockRestoredDynamoDBTableClient_Expecter{mock: &_m.Mock}
}

// RestoreAwsDynamodbTable provides a mock function for the type MockRestoredDynamoDBTableClient
func (_mock *MockRestoredDynamoDBTableClient) RestoreAwsDynamodbTable(embed *string, body models.RestoreAwsDynamodbTableV1Request) (*models.RestoreDynamoDBTableResponse, *apiutils.APIError) {
	ret := _mock.Called(embed, body)

	if len(ret) == 0 {
		panic("no return value specified for RestoreAwsDynamodbTable")
	}

	var r0 *models.RestoreDynamoDBTableResponse
	var r1 *apiutils.APIError
	if returnFunc, ok := ret.Get(0).(func(*string, models.RestoreAwsDynamodbTableV1Request) (*models.RestoreDynamoDBTableResponse, *apiutils.APIError)); ok {
		return returnFunc(embed, body)
	}
	if returnFunc, ok := ret.Get(0).(func(*string, models.RestoreAwsDynamodbTableV1Request) *models.RestoreDynamoDBTableResponse); ok {
		r0 = returnFunc(embed, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.RestoreDynamoDBTableResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*string, models.RestoreAwsDynamodbTableV1Request) *apiutils.APIError); ok {
		r1 = returnFunc(embed, body)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(*apiutils.APIError)
		}
	}
	return r0, r1
}

// MockRestoredDynamoDBTableClient_RestoreAwsDynamodbTable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreAwsDynamodbTable'
type MockRestoredDynamoDBTableClient_RestoreAwsDynamodbTable_Call struct {
	*mock.Call
}

// RestoreAwsDynamodbTable is a helper method to define mock.On call
//   - embed *string
//   - body models.RestoreAwsDynamodbTableV1Request
func (_e *MockRestoredDynamoDBTableClient_Expecter) RestoreAwsDynamodbTable(embed interface{}, body interface{}) *MockRestoredDynamoDBTableClient_RestoreAwsDynamodbTable_Call {
	return &MockRestoredDynamoDBTableClient_RestoreAwsDynamodbTable_Call{Call: _e.mock.On("RestoreAwsDynamodbTable", embed, body)}
}

func (_c *MockRestoredDynamoDBTableClient_RestoreAwsDynamodbTable_Call) Run(run func(embed *string, body models.RestoreAwsDynamodbTableV1Request)) *MockRestoredDynamoDBTableClient_RestoreAwsDynamodbTable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *string
		if args[0] != nil {
			arg0 = args[0].(*string)
		}
		var arg1 models.RestoreAwsDynamodbTableV1Request
		if args[1] != nil {
			arg1 = args[1].(models.RestoreAwsDynamodbTableV1Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRestoredDynamoDBTableClient_RestoreAwsDynamodbTable_Call) Return(restoreDynamoDBTableResponse *models.RestoreDynamoDBTableResponse, aPIError *apiutils.APIError) *MockRestoredDynamoDBTableClient_RestoreAwsDynamodbTable_Call {
	_c.Call.Return(restoreDynamoDBTableResponse, aPIError)
	return _c
}

func (_c *MockRestoredDynamoDBTableClient_RestoreAwsDynamodbTable_Call) RunAndReturn(run func(embed *string, body models.RestoreAwsDynamodbTableV1Request) (*models.RestoreDynamoDBTableResponse, *apiutils.APIError)) *MockRestoredDynamoDBTableClient_RestoreAwsDynamodbTable_Call {
	_c.Call.Return(run)
	return _c
}
